### ISSUE TITLE
gcc compilation problem

### ISSUE THREAD

**Issue by hkaiser** [pybind/pybind11#1069]
This code:

    pybind11::object func = ...;
    pybind11::dict d = func.attr("__class__").attr("__dict__");

compiles for MSVC and clang (and works as expected) but causes a compiler error for gcc 6 and gcc 7 complaining about not being able to convert a `str_attr_accessor` to a `dict`. I'm not sure if I'm trying to do the right thing here, so this might not be a real issue, just my ignorance.

**Comment by dean0x7d** [comment]
GCC is correct here. Clang 4.0 also fails to compile this. It's because the standard doesn't allow chaining user-defined implicit conversions. In this case: `detail::accessor` -> `py::object` -> `py::dict`. This should be fixed in #1076.

BTW `auto d = obj.attr("__dict__").cast<py::dict>()` also works (for those of us using the almost-always-auto style).

**Comment by hkaiser** [comment]
Thanks for your help, I clearly don't know enough about pybind11 yet..

**Comment by dean0x7d** [comment]
Knowledge of implementation details like `detail::accessor` shouldn't really be required to use the library. From a user's perspective, if it works for `py::object` there really isn't any reason to expect a compiler error for `py::dict`. It's definitely a real issue. The fix (#1076) will be in v2.2.1.
