### ISSUE TITLE
Casting of `std::string *` fails

### ISSUE THREAD

**Issue by r-owen** [pybind/pybind11#1081]
## Issue description

I have a C++ function that takes one argument: a bare pointer to a `std::string`. The pybind11 wrapper uses `nullptr` as the default for this argument. In Python the code fails with a type error if I omit the argument or use None, but works if I specify a string.

Modifying the example below so the test function takes `char const *` instead of `std::string const *` works as expected. So there are workarounds.

## Reproducible example code

C++ code and pybind11 wrapper
```
#include <iostream>
#include <string>
#include <pybind11/pybind11.h>

namespace py = pybind11;
using namespace pybind11::literals;

// replacing `std::string` with `char` makes this code work as expected
bool testStringPtr(std::string const *name) {
    return static_cast<bool> (name);
}

PYBIND11_PLUGIN(test) {
    py::module mod("test");

    // using NULL instead of nullptr gives the same result
    mod.def("testStringPtr", testStringPtr, "name"_a = nullptr);
}
```

Python code
```
import test
printt test.testStringPtr("hello")  # prints True
print test.testStringPtr()  # should print False, but fails with TypeError
```

**Comment by YannickJadoul** [comment]
There's two steps to this: 1. `nullptr` gets converted into a Python `None` object. 2. `std::string*` does not accept `None` since this is a custom conversion between `str` and `std::string` (https://pybind11.readthedocs.io/en/stable/advanced/functions.html#allow-prohibiting-none-arguments is only about "a C++ type registered with `py::class_`").

Arguably, this is not very consistent, so it might be nice to make consistent during a rework of the casters. However, for now, `std::optional` (or `boost::optional`) will do the job.

It's been almost three years :confused: , so I'll close this now, I guess.

**Comment by linrongbin16** [comment]
Hi @YannickJadoul , I want to return a custom struct as a python object, which also could be none. I have tried two API:
```C++
struct Database {
UserModel *get_user(const std::string &user_name) const;
std::optional<UserModel> get_user(const std::string &user_name) const;
};
```
But it seems none of these two API works.
Would you please help me?
