### ISSUE TITLE
PYBIND11_MODULE namespace clash

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#1104]
In PYBIND11_MODULE, if the name is also a namespace, compilation fails.  FWIW this was not a problem with the old-school PYBIND11_PLUGIN

E.g.:
```
#include <ChebMix/ChebMix.h>// (defining the ChebMix namespace)
...
PYBIND11_MODULE(ChebMix, m) {
    m.doc() = "ChebMix module";
    init_ChebTools(m);
    init_ChebMix(m);
}
```
yields
```
D:\Code\ChebMix\src\pybind11_wrapper.cpp(156): error C2882: 'ChebMix': illegal use of namespace identifier in expression
```

Is there a solution or workaround?

**Comment by YannickJadoul** [comment]
That is rather weird, because I also use the same name for my module name as for my main C++ namespace (and pybind11 v2.3, and `PYBIND11_MODULE`).

I assume you have made sure that since the last update, `PYBIND11_PLUGIN` still works (except for the deprecation message)?

Could you maybe intercept and show the output from the preprocessor, so we can see exactly where the problem for the compiler is?

`ChebMix` isn't some kind of macro definition, or something like that, either?

**Comment by ianhbell** [comment]
I also tried to move the implementation into another file and leave only these contents to remove namespaces completely:
``` C++
#include <pybind11/pybind11.h>

// Prototypes for the module initializers
void init_ChebTools(pybind11::module &);
void init_ChebMix(pybind11::module &);

PYBIND11_MODULE(ChebMix, m) {
    m.doc() = "ChebMix module";
    init_ChebTools(m);
    init_ChebMix(m);
}
```
and I get a new mysterious error
```
     D:\Code\ChebMix\src\pybind11_wrapper.cpp(7): error C2065: 'ChebMix': undeclared identifier
```
I tried the same thing with a module name of ``example`` as well, same error

MSVC 2014 for python 3.6 FWIW

**Comment by ianhbell** [comment]
And pybind11 2.2.1

**Comment by ianhbell** [comment]
Appears this was a git submodule falling out of sync on my side.  All is well.
