### ISSUE TITLE
Passing (n x 1) numpy arrays as vectors in Eigen

### ISSUE THREAD

**Issue by m-chaturvedi** [pybind/pybind11#1105]
## Issue description
The code below doesn't work with the current master of Pybind11, it used to work before ( at least at this commit: d534bd670e7de67bbc93999b6d24861bc3afd7a7 )
It fails with `incompatible function arguments` with the current master.

## Reproducible example code

```
#include <pybind11/pybind11.h>
#include <pybind11/eigen.h>
#include <iostream>
typedef Eigen::VectorXd Vec;

namespace basics {
        class MyClass{
                public:
                        MyClass() {}; 
                        void f(Vec &A, Vec &B) {}
        };  
}

namespace py = pybind11;
PYBIND11_PLUGIN(basics) {
        py::module m("basics", "pybind11 basics module");

        py::class_<basics::MyClass>(m, "MyClass")
                .def(py::init())
                .def("f",[](basics::MyClass& myclass, Vec& x, Vec& y){ 
                                return myclass.f(x,y);
                                })  
        ;   
        return m.ptr();
}

-----------------
# Python Code
import numpy as np
from basics import *
import pdb 

if(__name__ == "__main__"):
    x = MyClass();
    a = np.ones((7,1))
    b = np.ones((7,1))
    x.f(a, b)
```

**Comment by jagerman** [comment]
I've bisected this down to one of 627da3f135d3e01396f4ae911dc15145c1856cf0, b68959e822a619d1ad140f52c7197a29f4e6a06a, d400f60c96312f32fafcb15168bbf56970ff3d3a, 
30d43c4992f90ac7592fdbedd56c332717278c91.

(I couldn't bisect further because none of those currently build the test code)

I suspect b68959e822a619d1ad140f52c7197a29f4e6a06a - it looks like the numpy copy into the eigen array is failing, but I'm trying to figure out why.

**Comment by jagerman** [comment]
Thanks for the report; this should be fixed now in master.
