### ISSUE TITLE
Deal with const wchar_t* and std::wstring

### ISSUE THREAD

**Issue by hulucc** [pybind/pybind11#113]
It seems that const char * and std::string would be converted to unicode string automatically in python.
But what i'm supposed to do with const wchar_t* and std:wstring?

**Comment by wjakob** [comment]
It's not currently supported -- you'll have to write a converter analogous to that of std::string/char * in cast.h -- patches are welcomed, it's not a priority for me.

**Comment by polyvertex** [comment]
This is just from the top of my head, don't take it for granted... But it's quite straightforward to do in Python3 anyway.

Conversion from `wchar_t*` to `PyObject` in Python 3.3+: `PyUnicode_FromWideChar`. Otherwise, I believe you'll have to convert your wide string to UTF-8 first IIRC.

To convert it the other way around, you have `PyUnicode_Check` that helps you to validate the nature of the `PyObject` first, then `PyUnicode_AsWideChar` or `PyUnicode_AsWideCharString` depending on how you deal with memory allocation.

**Comment by wjakob** [comment]
There is a PR for this feature. Note that everything needs to work for Python 2.7 as well....

**Comment by wjakob** [comment]
This feature is available now.
