### ISSUE TITLE
errors with python on macOS sierra `cpython-36m-darwin.so`

### ISSUE THREAD

**Issue by abitofalchemy** [pybind/pybind11#1165]
## issue description
Just trying to do a compile call like so: 
> c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` example.cpp -o example `python3-config --extension-suffix`

This is the error I get:
`clang error no such file or directory cpython-36m-darwin.so`
Which is caused by this call: `python3-config --extension-suffix`

is there a way to fix this?

**Comment by jagerman** [comment]
I suspect you have a space between `example` and `` `python3-config --extension-suffix` ``, but it should be without a space:

``c++ ... example.cpp -o example`python3-config --extension-suffix` ``

Or if you prefer, you can use `$(...)` instead of the backticks:

``c++ -O3 -Wall -shared -std=c++11 -fPIC $(python3 -m pybind11 --includes) example.cpp -o example$(python3-config --extension-suffix)``

That might be a better way to write it in our documentation.

**Comment by soulslicer** [comment]
How does one fix this through cmake

**Comment by henryiii** [comment]
I think this has been documented/improved in the last three years - reopen if there's still a problem!
