### ISSUE TITLE
Operator overloading square bracket []

### ISSUE THREAD

**Issue by chinmoykulkarni** [pybind/pybind11#1179]
Hi,
I am unable to find any example of how to overload the square bracket operator [] 
eg.
    Foo operator[](long indx){return vec[indx];} where vec is a vector from constructor.

However, In pybind how would I write the same?
Currently, I have this
    py::class_<Bar>(m,"Bar")
        .def(py::inint<>())
        .def(Foo [] long());
    error: expected primary-expression before '[' token
    error: expected primary-expression before ']' token

However, this does not work.
I have also tried 
    .def(Foo [long()]);
    error: expected primary-expression before '[' token if done this way. while neither work

**Comment by henryiii** [comment]
Hi, consider trying the Gitter for pybind first for simple questions, you might get answers faster :).

You'll need to provide `__getitem__` and `__setitem__` (Since Python doesn't have references, the case `Foo[x] = y` is special). If you want to wrap an `operator []`, here is an example that might work for `__getitem__`:

```cpp
.def("__getitem__", &Foo::operator []);
```

And, in case it doesn't, this lambda function will work:

```cpp
.def("__getitem__",[](Foo& self, long i) {return self[i];});
```

You'll have to use the lambda function approach for `__setitem__`:

```cpp
.def("__setitem__",[](Foo& self, long i, T value) {self[i] = value;});
```

Where T is the type for your value in the vector.
