### ISSUE TITLE
Suprising overload resolution with default value for const char * of nullptr

### ISSUE THREAD

**Issue by davidhewitt** [pybind/pybind11#1222]
## Issue description

Overload with default value of nullptr for a const char* seems to take low priority as if it requires a conversion.

## Reproducible example code

With the following code

    struct Foo;

    py::class_<Foo> (m, "Foo")
      .def (py::init (
        [] (const std::string &, const char *)
        {
          std::cout << "const char * constructor called" << std::endl;
          return Foo ();
        }),
        py::arg ("string"),
        py::arg ("const char *") = nullptr)
      .def (py::init (
        [] (const py::object &)
        {
          std::cout << "object constructor called" << std::endl;
          return Foo ();
        }));

According to the description of overload resolution in the docs, I was hoping that `Foo('hello')` would call the `const char *` constructor, but:

    >>> import mymodule
    >>> mymodule.Foo("hello")
    object constructor called
    <mymodule.Foo object at 0x7fb9c7110228>

    >>> mymodule.Foo("hello", None)
    const char * constructor called
    <mymodule.Foo object at 0x7fb9c7110298>

The constructor works when I pass None explicitly, but not when I leave it to the default value?

Thanks for this awesome library!

David

**Comment by jagerman** [comment]
Yes, we explicitly defer `None` to the converting pass for `char *` arguments, because it isn't obviously a definite match for a `char *`, and setting a `char *` to a nullptr is a little out of the ordinary, so we want to deprioritize it in case there is something else (like a `py::object` or `py::none` argument) that makes more sense as a match.

The other thing happening here, which isn't always immediately obvious, is that defaults specified via `py::arg`s are always Python object, which means a C++ value gets implicitly cast to Python when the default is stored.  In this case, `py::arg("a") = nullptr` is really the same thing as `py::arg("a") = py::cast(nullptr)`, which itself is equivalent to `py::arg("a") = py::none()`.

As for working around it, you can *also* add an overload that takes a `py::none`, then invokes the C++ code as desired with an explicit `nullptr`.  (Though obviously that scales badly if there are several `char *` arguments where you would want `nullptr` values).

**Comment by davidhewitt** [comment]
That makes sense, thanks very much. I'll probably go for the py::none() route.
