### ISSUE TITLE
possible bug involving string_view and utf-8

### ISSUE THREAD

**Issue by zpz** [pybind/pybind11#1252]
file column.cc:

```
#include <experimental/string_view>
#include <variant>

#include <pybind11/pybind11.h>

namespace py = pybind11;


class Column {
    private:
        std::variant<int, double, std::string_view> value;

    public:
        Column(int x) : value{x} {}
        Column(double x) : value{x} {}
        Column(std::string_view x) : value{x} {}

        inline bool is_int() const { return 0 == value.index(); }
        inline bool is_double() const { return 1 == value.index(); }
        inline bool is_string() const { return 2 == value.index(); }

        inline int get_int() const { return std::get<int>(value); }
        inline double get_double() const { return std::get<double>(value); }
        inline std::string_view get_string() const { return std::get<std::string_view>(value); }
};


PYBIND11_MODULE(column, m) {
    py::class_<Column>(m, "Column")
        .def(py::init<int>())
        .def(py::init<double>())
        .def(py::init<std::string_view>())
        .def_property_readonly("is_int", &Column::is_int)
        .def_property_readonly("is_float", &Column::is_double)
        .def_property_readonly("is_string", &Column::is_string)
        .def("_get_int", &Column::get_int)
        .def("_get_float", &Column::get_double)
        .def("_get_string", &Column::get_string);
}
```

file app.py in the same directory:

```
from column import Column


def _column_value(self):
    if self.is_int:
        return self._get_int()
    if self.is_float:
        return self._get_float()
    if self.is_string:
        return self._get_string()


setattr(Column, 'value', property(_column_value))
```

Makefile:

```
CC = g++
CCFLAGS = -fPIC -std=c++17 -Wall -O2
LDFLAGS = -shared
INCLUDES = -I./ -I/usr/local/include/python3.5m

TARGET = column.so

all: $(TARGET)


$(TARGET): column.o
	$(CC) ${LDFLAGS} -o $@ $^


%.o: %.cc
	$(CC) -c $(CCFLAGS) $(INCLUDES) $< -o $@


clean:
	rm -f column.o $(TARGET)
```

`make` runs smoothly. In same directory, launch python interactively, did the following session:

```
In [11]: from app import Column

In [12]: Column('abc').value
Out[12]: 'abc'

In [13]: Column(102).value
Out[13]: 102

In [14]: Column(38.7).value
Out[14]: 38.7

In [15]: x = ['abc', 102, 38.7]

In [16]: y = [Column(v) for v in x]

In [17]: y[2].value
Out[17]: 38.7

In [18]: y[1].value
Out[18]: 102

In [19]: y[0].value
Out[19]: 'РQ'

In [20]: y[0].value
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-20-3893cef2e553> in <module>()
----> 1 y[0].value

~/work/src/pybind11bug/app.py in _column_value(self)
      8         return self._get_float()
      9     if self.is_string:
---> 10         return self._get_string()
     11 
     12 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 1: invalid start byte
```

Note the behavior is not totally reproducible. At one point `y[0].value` returns `PQ` while `abc` is expected. At another point it crashes.

pybind11 2.2.1; python 3.5.4; g++ 7.2.0

**Comment by zpz** [comment]
Another session:

```
In [1]: from app import Column

In [2]: y = [Column('abc'), Column(102), Column(38.7)]

In [3]: y[0].value
Out[3]: '\x00bc'

In [4]: y[0].value
Out[4]: '@ɏ'

In [5]: y[0].value
Out[5]: '@ɏ'

In [6]: y[0].value
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-3893cef2e553> in <module>()
----> 1 y[0].value

~/work/src/pybind11bug/app.py in _column_value(self)
      8         return self._get_float()
      9     if self.is_string:
---> 10         return self._get_string()
     11 
     12 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte

In [7]: Column('abc').value
Out[7]: 'abc'
```

**Comment by bmerry** [comment]
This seems expected to me: the Column class is holding a `string_view`, instead of keeping a copy of what it's given. The memory belongs to a temporary that is constructed by pybind11 and disappears when the constructor returns, so the Column is referencing undefined memory.

**Comment by jagerman** [comment]
Agree with @bmerry.  A `string_view` is really meant to be an in-transit type, not meant to be stored beyond the duration of a function call unless you have some external guarantee that the data it's referencing will stay valid for the life of the `string_view` (`string_view` does not provide any such guarantee itself).  In most cases in C++, the valid lifetime is just the duration of the function call that accepts the `string_view`.  You are seeing it sometimes "work" here because the string view is referencing invalid memory that, just by luck, hasn't been overwritten with something else yet.  The wrong output and the decoding failure are happening because it *has* been overwritten.

Changing your `variant` to hold a `std::string` rather than a `string_view` is probably what you want to do here.  You can still accept a `string_view` (a `std::string` can be constructed from one), and can still return it, but when returning it needs to be a `string_view` into a `string` that you own.

**Comment by zpz** [comment]
Makes sense.  However string_view I believe is useful when I run the code totally in C++ (that's my use case: Python is one way to use it; I need to use it purely in C++ as well). One idea is to save the string in a Python wrapper class, then create the C++ side of class

```
from column import Column as _Column

def _column_value(self):
    if self.is_int:
        return self._get_int()
    if self.is_float:
        return self._get_float()
    if self.is_string:
        return self._get_string()

setattr(_Column, 'value', property(_column_value))

class Column:
    def __init__(self, x):
        self.x = x
        self.col = _Column(self.x)

    @property
    def value(self):
        return self.col.value
````

Then on Python side essentially use `Column` (as a wrapper for `_Column`). However, the problem persists. This baffles me. My thinking is even if `Column(x)` gets a temporary `x`, now `x` is stored in `Column`, so it won't get destroyed in the lifetime of `Column`. Any pointers?

**Comment by bmerry** [comment]
The problem is that you're storing a Python `str` in `self.x`, but the `string_view` is pointing to memory owned by a temporary `bytes` containing the UTF-8 encoding (constructed by pybind [here](https://github.com/pybind/pybind11/blob/add56ccdcac23a6c522a2c1174a866e293c61dab/include/pybind11/cast.h#L1139)), which goes away at the end of the call even if you're keeping the `str` alive.

If you had the wrapper class do the UTF-8 encoding and keep a reference to the `bytes`, then passed that to the underlying constructor, it would probably work.

**Comment by zpz** [comment]
Yes, storing `bytes` works. Another solution is to have a 'string' constructor and a 'string_view' constructor on the C++ side, and only expose the 'string' constructor to Python.
