### ISSUE TITLE
What is the correct way to bind copy constructor when class has Python`trampoline`?

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#1277]
Dear Pybind11 developers,

   I am trying to create bindings for copy-constructor for non-abstract class that have Python trampoline structure. What is the correct way to do that?

  For class `A` I have tried:
```cl.def( pybind11::init( [](A const &o){ return new A(o); }, [](A_trampoline const &o){ return new A_trampoline(o); } )```

 but that produce compilation error. So instead i just bind two 'copy-like' constructors:

```
cl.def( pybind11::init( [](A const &o){ return new A(o); } );
cl.def( pybind11::init( [](A_trampoline const &o){ return new A_trampoline(o); } )
```
  Is this the right way to do this?

Thanks,

**Comment by jagerman** [comment]
The dual-argument `init` is for deciding between the constructor paths to follow based on how the constructing class is being used in Python, but *not* based on the arguments to that constructor (which is why identical argument types are enforced).  So the first one gets invoked when the Python caller is initializing the class directly, while the second one gets invoked when the class is being initialized as a based class of a Python subclass initialization.

If you want overload resolution--i.e. to do something differently when the *argument* is a different type, then you need to use an overload, as you provided.  Though I think you'll have to move the trampoline constructor first, however, so that it gets tried before the based class constructor.

There are actually *four* possible cases to consider (and so you might want to use two overloads, each providing a pair of init functions):
- class invoked directly, argument is a trampoline instance
- class invoked via Python inheritance, argument is a trampoline instance
- class invoked directly, argument is not a trampoline
- class invoked via Python inheritance, argument is not a trampoline
Your overloads would first decide between (1,2) or (3,4), then the dual-init would let your code distinguish between (1,2) on the first overload and (3, 4) on the second.

It's quite possible you don't need to have 4 separate lambdas, however: case 1 and 3, for instance, are probably going to be identical (i.e. invoking the base copy constructor, whether or not the argument is actually a trampoline instance).

Or, alternatively, you might want invocation from a trampolined instance to produce a trampoline even when a trampoline isn't needed, in which case 2 and 3 will be the same.

**Comment by lyskov** [comment]
I see, - thank you for detailed explanation @jagerman !
