### ISSUE TITLE
Template function with Eigen

### ISSUE THREAD

**Issue by skulumani** [pybind/pybind11#1324]
## Issue description

I'm trying to extend the help given in #199 for use with templated Eigen functions as demonstrated in the [Eigen documentation](https://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html).

The following example is a template version of a function taking eigen parameters.

~~~
#include <Eigen/Dense>
#include <iostream>

template<typename Derived> 
void scale_vector_template(Eigen::PlainObjectBase<Derived>& v, const int scale) {
    v  = v * scale;
}

int main() {
    Eigen::Vector3d v;
    v << 1, 2, 3;
    scale_vector_template(v, 1);
    std::cout << v << std::endl;
}

~~~

Here is a version with the Pybind macro for exposure to Python.

~~~
#include <Eigen/Dense>
#include <iostream>
#include <pybind11/eigen.h>
#include <pybind11/pybind11.h>

namespace py = pybind11;

template<typename Derived> 
void scale_vector_template(Eigen::PlainObjectBase<Derived>& v, const int scale) {
    v  = v * scale;
}

PYBIND11_MODULE(py_template, m) {
    m.doc() = "Python example bindings with eigen templates";
    m.def("scale_vector_template", &scale_vector_template<Eigen::Matrix<double, -1, 3> >);
}

~~~

This results int the following errors.

~~~
/usr/include/c++/5/tuple:105:22: error: use of deleted function ‘pybind11::detail::type_caster<Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 3> >, void>::type_caster()’  
~~~

Thank you

**Comment by jagerman** [comment]
The issue with trying to bind an eigen base class (like `PlainObjectBase`) is that we don't actually *have* an instance of such a class: we have to be able to create something that either copies or directly references numpy data that we can pass to the function.  More technically, we only support Eigen types that are default-constructible, and the `PlainObjectBase` (and related) templated classes are not.

While we possibly could, in theory, create something that fits (e.g. constructing a `Matrix<double, -1, 3>` instance in your example), this is quite difficult to do robustly, and is often *not* what the creator of the API intended.  Your example, for instance, would fail because `v` could only be a temporary that exists for the lifetime of the bound method.  What that means if that if your existing API definitely requires such an argument, you'll need to do such a conversion yourself, via something like:

```C++
m.def("scale_vector", [](Matrix<double, -1, 3> d) { scale_vector_template(d); /* Now do something with the updated d */ });
```

However, what we *do* provide, which is very powerful (even in regular C++ Eigen use) is quite robust support for `Eigen::Ref` objects, as in the "How to write generic, but non-templated function?" section of the Eigen documentation you linked to.  (Also see the [pybind documentation on eigen support](http://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html), which covers this in quite a bit of detail).  These *do* map directly back into numpy arrays, when possible (see the pybind docs for details), allowing you to do things like:

```C++
template<typename D> 
void scale_vector_template(Eigen::Ref<D> v, const int scale) {
    v  = v * scale;
}

// ...

m.def("scale_vector_template", &scale_vector_template<Eigen::Matrix<double, -1, 3>>);
```

You can also, of course, bind a function that takes a `Eigen::Matrix` type directly, but the `Ref` approach really is the more powerful approach to avoid copying between objects.  (That said, there are some caveats: by default Eigen uses column-major order, but numpy defaults to row-major order, and sometimes (particular in the numpy -> Eigen directly) there is a clash.  Again see the docs for details and solutions).

**Comment by skulumani** [comment]
Thank you for the great discussion and comment.

**Comment by YannickJadoul** [comment]
Question has been answered, so closing.
