### ISSUE TITLE
return_value_policy for properties

### ISSUE THREAD

**Issue by looooo** [pybind/pybind11#133]
Is it possible to add return value policy options for "def_property", "def_property_readonly".... I couldn't find anything in the docs, so I am not sure if this is already possible.

thanks
Lorenz

**Comment by wjakob** [comment]
the return value there is always reference_internal. I think that's the only one which makes sense, no?

**Comment by looooo** [comment]
thanks for the answer,
I thought my problem is related to the return_value_policy, but actually it isn't. I will try to make a minimal test.
This issue can be closed I think.

**Comment by looooo** [comment]
I think for def_property / def_property_readonly it would make sense to have the option to specify the return_policy. At least in my case it would have been nice. I have tried many things, but in the end had to use a pybind11::return_value_policy::copy to get some bindings working....

**Comment by wjakob** [comment]
Actually..., looking a the definitions: you **can** override the return value property of def_readonly et al.

For the def_property variants, you have to specify a cpp_function (look at the way they are called in pybind11.h), and there you can also provide a return value property explicitly. So I'm really not sure what the issue is here..

**Comment by looooo** [comment]
Thanks for the information, this worked.
