### ISSUE TITLE
How to test if a key exists in py::dict

### ISSUE THREAD

**Issue by xsh6528** [pybind/pybind11#1340]
I want to do something similar to
  
```
if (kwargs["switch"] != py::none()) {
    switch = switch["shuffle"];
}
```

**Comment by jagerman** [comment]
You can check for existence of the key with `obj.contains`:
```C++
if (kwargs.contains("switch")) {
    // ...
}
```
and for the value equaling none with `obj.is_none()`:
```C++
if (!kwargs["switch"].is_none()) {
    // ...
}
```
But note that, like Python, key existence and value equaling None are different: it is possible for a dictionary to contain the key "switch" with a value of `None`, which is different than the dictionary not containing the key.  So you may actually want:
```C++
if (kwargs.contains("switch") && !kwargs["switch"].is_none()) {
    // ...
}
```

It's also possible to do a `None` check using `!val.is(py::none())` rather than `!val.is_none()`, but it's slightly more verbose, and slightly less efficient.

**Comment by ecolss** [comment]
@jagerman what if I want the key to be integer, not string, looks like it cannot compile at all

**Comment by cielavenir** [comment]
@ecolss @jagerman it should be addressed by https://github.com/pybind/pybind11/pull/4004 . I don't know why it is taking time.

**Comment by cielavenir** [comment]
though you can use `dic[py::cast(num)]`
