### ISSUE TITLE
Does pybind11 attempt to reuse moved-out objects?

### ISSUE THREAD

**Issue by iwrinc** [pybind/pybind11#1385]
(I apologize for not providing an SSCCE. Currently, this question is somewhat theoretical and it would be more appropriate to ask it on some pybind11 dev forum, but I could not find one.)

Some of the C++ objects I wrap have the following unfortunate feature: after being moved-out, they get unusable (but they are still destroyable). Meaning that the following would trigger an assert:
auto y = std::move(x);
x = y; // assert!

It seems that pybind11 wrappers consistently trigger the above assert. In addition, as far as I can see, the state of all the objects in the C++ layer remains valid at that point, so I suspect that some pybind object might attempt to reuse a moved-out object it wraps.
Is it really the case? If yes, where does it happen exactly?

Thanks.

**Comment by bstaletic** [comment]
> it would be more appropriate to ask it on some pybind11 dev forum

You can always come to gitter. https://gitter.im/pybind/Lobby

For the record, it could be the case, but I have no idea. The remark by @oremanj about "unspecified but valid" is a good one. A well behaved type would allow you to call any operation on it that has no preconditions, such as `std::vector<T>::size()`.

Anyway, I'm going to close this, since @iwrinc never continued the discussion. If there's still a problem of some sort, reopen with a minimal example that can show the problem.
