### ISSUE TITLE
Wrapping a const singleton

### ISSUE THREAD

**Issue by daveah** [pybind/pybind11#1418]
## Issue description

When wrapping a singleton that returns its instance as a const reference, I've been unable to get a version using a const unique_ptr to compile.

## Reproducible example code

If I have a simple singleton such as:

```
class Singleton1 {
public:
  static Singleton1& instance();
private:
  Singleton1();
  ~Singleton1();
};
```

I can wrap this relatively easy (following comments in issue 947).

```
py::class_<Singleton1, std::unique_ptr<Singleton1, py::nodelete>>(m, "Singleton1")
  .def(py::init([](){ return std::unique_ptr<Singleton1, py::nodelete>(&Singleton1::instance()); }));
```

If I take a similar singleton that returns the reference by const reference:

```
class Singleton2 {
public:
  static const Singleton2& instance();
private:
  Singleton2();
  ~Singleton2();
};
```

I would expect the following code to work:

```
py::class_<Singleton2, std::unique_ptr<const Singleton2, py::nodelete>>(m, "Singleton2")
  .def(py::init([](){ return std::unique_ptr<const Singleton2, py::nodelete>(&Singleton2::instance()); }));
```

However, it fails with a series of error messages that look like either `unique_ptr<const T>` is not supported in pybind11 as a holder, or that `py::nodelete` doesn't work with a `unique_ptr<const T>`.  I've tried using either of the following:

```
PYBIND11_DECLARE_HOLDER_TYPE(T, std::unique_ptr<const T>);
PYBIND11_DECLARE_HOLDER_TYPE(T, (std::unique_ptr<const T, py::nodelete>));
```

However, this fails.

The only code I've got to compile is the very hacky:

```
py::class_<Singleton2, std::unique_ptr<Singleton2, py::nodelete>>(m, "Singleton2")
  .def(py::init([](){ return std::unique_ptr<Singleton2, py::nodelete>(&const_cast<Singleton2&>(Singleton2::instance())); }));
```

Is there any way to properly support const singletons?

**Comment by EricCousineau-TRI** [comment]
There may be two issues to resolve here:
(1) If you have a proper singleton, then you should perhaps be wrapping a method that returns `const T*` in lieu of `unique_ptr<T>` or `unique_ptr<const T>`, since the actual object is owned via the `Singleton2::instance()` method.
(2) `pybind11` (and Python in general) do not have the intrinsic ability to provide `const` views into an object. See https://github.com/pybind/pybind11/issues/717 for some discussion on it.

(1) is your main blocker. To bind a singleton, you should do something like this:
```
py:::class_<Singleton>  // We don't care about the holder, because Python will never own this instance.
   // Do not define `init`; if you can't construct the class publicly in C++, you shouldn't construct it in Python.
   .def("instance", &Singleton::instance, py::return_value_policy::reference);  // This returns a pointer to the singleton; it's lifetime is dictated by `Singleton::instance()`
```

Be careful on lifetime; consider using something like `never_destroyed` if the destruction can do bad things:
http://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables

(2) shouldn't be that much of a problem; just be careful on what you bind and expose to Python, and you should be good to go. If you *really* need fanciful `const` views, you'll need to implement your own mechanism, either following the suggestions in #717 or something else.

**Comment by YannickJadoul** [comment]
No further reaction to @EricCousineau-TRI's excellent advice. Closing.

Thanks, @EricCousineau-TRI!
