### ISSUE TITLE
Access Python Exception object

### ISSUE THREAD

**Issue by espositofulvio** [pybind/pybind11#1614]
## Issue description

When catching a Python exception from C++, there is no way to access the exception data. Python exceptions are converted to error_already_set, but its members are private and there's no way to access the actual exception data in case the value member is set as for StopIteration.

**Comment by DenisSalem** [comment]
Same issue here. Well, it's more like a missing feature than an issue, but still.

Regards.

**Comment by bstaletic** [comment]
There's currently a pull request that provides getters for the private members.

**Comment by YannickJadoul** [comment]
Now that `error_already_set` has `value()` and `type()` are there, after #1641, you should be able to query these:

```c++
        try {
                py::exec("raise ValueError(42)");
        }
        catch (const py::error_already_set &e) {
                py::print(e.value().attr("args"));
        }
```

This nicely prints a tuple `(42,)`.

> There is no way as far as I know to bind C++ exception class attributes

No, because `py::error_already_set` is an wrapper around a Python exception.

> bind C++ exception class attributes to the newly created python exception, like you would do with def_readwrite.

If you mean adding methods and properties to the custom C++ exceptions exposed to Python, that is a long standing feature request (can't immediately fine one, but I'm sure there's one or more issues), but far from easy to implement. But it doesn't seem like that's @espositofulvio's original question?

**Comment by espositofulvio** [comment]
Hi @YannickJadoul,
my question is fully addressed by this change. Thanks a lot!

**Comment by YannickJadoul** [comment]
Great! Thanks for confirming! :-)
