### ISSUE TITLE
PYBIND11_MODULE MSVC 2017 python 3.6 issue: Python Version mismatch

### ISSUE THREAD

**Issue by Mjang714** [pybind/pybind11#1620]
Hey,
 I was following the microsoft visual studio guide on how to setup a python wrapper for c++ via pybind11 here: https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2017 . However after following the instructions my PYBIND11_MODULE within MSVC 2017 seems to think that there is a python version mismatch. When I deprecated the project to use python 2.7 everything worked as expected. I was curious if anyone knew any solution to this since I would like to use python 3.6 or greater. I am relatively new to developing on Windows so sorry if my question seems a little basic. Thanks!!!!

**Comment by YannickJadoul** [comment]
We don't have enough information to say anything about this. What exactly was the error message? What versions of Python are in the settings?

I'll close this, since it's 1.5+ years old, but please reopen (or pass by [Gitter](https://gitter.im/pybind/Lobby) to ask a short question) if this is still an issue.
