### ISSUE TITLE
how to overwrite parent class's enum with same name?

### ISSUE THREAD

**Issue by steve3d** [pybind/pybind11#1624]
## Issue description

I'm binding a complex c++ library to python, in this lib, it has many inheritance, and for example
```
class A {
public:
     enum AEnum{...}
}

class B: public A {
public:
     enum AEnum{...}
}
```
in child class, there is a enum with exact same name with parent class, but it has different values. so in my binding code, I can bind these enum to each class, it compiles fine, but when in python, if I use `import testmodule`, then it throws an error about that `AEnum` is already defined.

So How could I export these different enums with same name, but in different class?

PS: I didn't use `py::enum_<xx>().export_values()`, I don't want any of these enum values in my root module.

**Comment by YannickJadoul** [comment]
I can confirm this issue:

```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

class A {
public:
        enum AEnum {
                X
        };
};

class B : public A {
public:
        enum AEnum {
                X,
                Y
        };
};

PYBIND11_MODULE(example, m)
{
        py::class_<A> classA(m, "A");
        py::class_<B, A> classB(m, "B");
        py::enum_<A::AEnum>(classA, "AEnum")
                .value("X", A::AEnum::X);
        py::enum_<B::AEnum>(classB, "AEnum")
                .value("X", B::AEnum::X)
                .value("Y", B::AEnum::Y);
}
```

The reason is because when registering `B::AEnum`, pybind11 is checking [`hasattr(classB, "AEnum")`](https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L920-L922), and it finds it in the base class. We should probably do a more strict check, here.

A ugly workaround is reasonably simple though: first register `py::enum_<B::AEnum>(classB, "AEnum")` and only then register `py::enum_<A::AEnum>(classA, "AEnum")`.
