### ISSUE TITLE
Autogenerate docstring + argument names as a pre-processing.

### ISSUE THREAD

**Issue by jdumas** [pybind/pybind11#1626]
Hi,

I was wondering whether it would be interesting to have some kind of script to generate bindings for a C++ function with a doxygen comment. Imagine I am documenting my C++ function as follows:

```cpp
///
/// Remesh a surface triangle mesh uniformly.
///
/// @param[in]  V     { #V x 3 input mesh vertices }
/// @param[in]  F     { #T x 4 input mesh tetrahedra }
/// @param[out] OV    { #OV x 3 output mesh vertices }
/// @param[out] OF    { #OF x F output mesh triangles }
///
/// @return     { True if ok }
///
bool remesh_uniform(const Eigen::MatrixXd &V, const Eigen::MatrixXi &F,
	Eigen::MatrixXd &OV, Eigen::MatrixXi &OF);
```

It should be possible to generate 1) the python docstring, and 2) the named arguments (`py::args()`) corresponding to this function by parsing the doxygen comment. This would facilitate generating an initial list of bindings, or updating documentation on both C++ side and python side for a given function.

I am wondering if such a project already exists? Would it be an interesting feature to have? I've looked around but I haven't found any reference to this specific use-case.

**Comment by jdumas** [comment]
I've found this [SO thread](https://stackoverflow.com/questions/34896122/how-to-avoid-redundancy-between-c-and-boostpython-docs) that talk about the issue for Boost.Python. Maybe something similar could be used for pybind11.

**Comment by EricCousineau-TRI** [comment]
pybind11 does have `mkdoc` for generating docstrings:
https://github.com/pybind/pybind11/blob/master/tools/mkdoc.py

I believe if you search for it, you'll find Wenzel's explanation for how to use it.

We're using it in our project, Drake, but modified it some to (a) avoid using a slew of macros and make a nested / hierarchy structure and (b) add some extra sugar for converting Doxygen -> Markdown. Example of what the generated doc looks like:
https://github.com/RobotLocomotion/drake/blob/6797d16eb4afbff608c8664b21f04037f2701fdc/tools/workspace/pybind11/test/sample_header_documentation.expected.h
Modified script:
https://github.com/RobotLocomotion/drake/blob/6797d16eb4afbff608c8664b21f04037f2701fdc/third_party/com_github_pybind_pybind11/mkdoc.py

It may not be the best workflow for docstrings due to a lot of coupling between header files and Python binding - and compiler errors look a tad mangy - but it gets the job done for now.

W.r.t. argument names, I supposed these structs could be modified to make a list of arguments (if we wanted to keep this to code-time generation).

---

That being said, it looks like you're potentially looking into actual binding generation, not just docstrings / argument name stuff. If we had a simpler API (that didn't involve so many pesky templates), we'd probably be using `Binder` or something related to that with using the actual clang C++ API:
https://pybind11.readthedocs.io/en/stable/compiling.html?highlight=binder#generating-binding-code-automatically

There are quite a few flavors of this type of things as well. For our project, I'd like to see if `libclang` Python bits provide enough non-buggy functionality to achieve this, but we may end up using one of these other techniques for automating our binding generation.

**Comment by jdumas** [comment]
Ah, Binder looks exactly like what I want! This looks great!

**Comment by YannickJadoul** [comment]
Seems to be solved. Thanks, @EricCousineau-TRI :-)
