### ISSUE TITLE
Eigen entity binding issue

### ISSUE THREAD

**Issue by phg1024** [pybind/pybind11#1681]
I was trying to bind private member accessors in the following way:
```cpp
#include <pybind11/eigen.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;
using namespace pybind11::literals;

class A {
 public:
  A() {}
  A(const std::string& name, const Eigen::Vector3f& v) : name(name), v(v) {}

  const std::string& get_name() const {
    return name;
  }
  void set_name(const std::string& in_name) {
    name = in_name;
  }

  const Eigen::Vector3f& get_v() const {
    return v;
  }
  void set_v(const Eigen::Vector3f& in_v) {
    v = in_v;
  }

 private:
  std::string name;
  Eigen::Vector3f v;
};

PYBIND11_MODULE(temp, m) {
  m.doc() = "Temp tests";

  py::class_<A>(m, "A")
      .def(py::init<>())
      .def(py::init<const std::string&, const Eigen::Vector3f&>())
      .def_property("name", &A::get_name, &A::set_name)
      .def_property("v", &A::get_v, &A::set_v);
}
```

and use it in the client code
```
a = A("foo", [0, 1, 0])
a.name += "bar"
a.name = a.name + "foobar"

# this does not work! it spits out this error
#     a.v += np.array([0, 1, 0])
# ValueError: output array is read-only
# a.v += np.array([0, 1, 0])
# a.v *= 2.0

# the following works though
a.v = a.v + np.array([0, 1, 0])
a.v = a.v * 2.0
print(a.name, a.v)
```

I was wondering what's the reason behind this. IMO `+=`, `*=` and the like should behave similarly to assignment operator, so it should translate to something equivalent to:
```cpp
a.set_v(a.get_v() + Eigen::Vector3f(0, 1, 0));
a.set_v(a.get_v() * 2.0);
```

Am I missing something here? Or is this not the right way to bind private data members? Thanks in advance!

**Comment by YannickJadoul** [comment]
This string gets copied (and is actually immutable, so the `__iadd__` method will not mutate the object itself), so the `const` return value of `get_name` doesn't matter, here.

The returned Eigen vector is returned as numpy array and isn't copying all internal values. Because it is returned as `const`, it will be a read-only numpy array and the `__iadd__` will give you that error (because `+=` for a numpy array actually wants to mutate the original array, rather than create a new array by adding and then reassigning). So there is a difference between `array = array + 42` and `array += 42` for numpy.

Apart from that, there's no problem, I believe.
