### ISSUE TITLE
pybind11 analog for java?

### ISSUE THREAD

**Issue by pwm1234** [pybind/pybind11#1739]
I have benefited significantly from using pybind11 to implement interoperability between python and C++. I now need to implement a similar wrapping of my C++ code from java. What is the java analog to pybind11? (I apologize for being a little off topic, but I have been unable to find an answer elsewhere. Thank you for your time and for your effort on pybind11--I really like it!)

**Comment by eacousineau** [comment]
Doing a quick pass, I'm not seeing anything out of the gates; may not be an active area of work for the community? (Disclaimer: I personally haven't programmed in Java at all since high school; I've only read through some of the Bazel build system's source code.)

I'm turning up some old projects, like:
https://github.com/nativelibs4java/JNAerator
https://github.com/nativelibs4java/nativelibs4java-

FTR, there are projects like `pybind` / `boost.python` for other languages that are under active development, e.g.
https://github.com/JuliaInterop/CxxWrap.jl

**Comment by jkhoogland** [comment]
You might want to have a look at [javacpp](https://github.com/bytedeco/javacpp)
This is a mature, straightforward approach to wrapping c++ code.

**Comment by pwm1234** [comment]
Thanks! javacpp seems to be the java equivalent to pybind11. (Although pybind11 documentation gives a better first impression!)
