### ISSUE TITLE
pybind11 broken with Py_LIMITED_API

### ISSUE THREAD

**Issue by rnburn** [pybind/pybind11#1755]
cast.h uses [PyTuple_SET_ITEM](https://github.com/pybind/pybind11/blob/master/include/pybind11/cast.h#L1412) but that function i sn't available in the limited api: https://github.com/python/cpython/blob/8ac6539d85b481fc6b5e9145446b07e591b2caba/Include/tupleobject.h#L57-L66

**Comment by wjakob** [comment]
Hi @rnburn,

there are *many* other functions that pybind11 uses that aren't part of the limited API (and there are no plans to support it).

**Comment by adalisk-emikhaylov** [comment]
We forked Pybind and made this work ourselves: https://github.com/meshinspector/mrbind-pybind11
They way we do it is by compiling small shim libraries for each Python version we need to support, then loading the appropriate one at runtime.

**Comment by LecrisUT** [comment]
I didn't search for the right keyword when opening #5652. Anyway this issue was open 6 years ago and it would be helpful to do a temperature check on this issue again. Tooling wise, FindPython should allow to add a test for this support.

@adalisk-emikhaylov in your investigation, how many changes are required and why do `ifdef` checks not suffice? Otherwise do you reckon you could make it a standalone implementation that this package could pull?

My main concern of the approach described there os that it seems to defeat the benefit of the SABI to be able to build only one wheel and be compatible with future python3 versions.

**Comment by adalisk-emikhaylov** [comment]
@LecrisUT

> why do `ifdef` checks not suffice? 

`#ifdef`s happen at compile-time, but we need to select the implementation at runtime. I kept the ifdefs, but had to move any functions that have them to the shim shared library (that is compiled separately for each minor python version, and then selected at runtime).

> how many changes are required 

You could diff my repo against the commit it was forked from. Quite a lot of changes, but most of them are mechanical.

> seems to defeat the benefit of the SABI to be able to build only one wheel and be compatible with future python3 versions

Yeah, this is unfortunate. The reason why we did it is to save storage space on pypi and decrease our build times.

> do you reckon you could make it a standalone implementation that this package could pull?

In theory I could rebase my fork onto the latest main, then that could be pulled, but I'm not sure it's a good idea.

Nanobind supports proper stable ABI for Python 3.12+, so doing this without shim libraries seems to be possible. Then pybind would be better off doing that, I think.
