### ISSUE TITLE
Compile failures with char8_t by MSVC under /std:c++latest(C++ 20) mode

### ISSUE THREAD

**Issue by QuellaZhang** [pybind/pybind11#1761]
Hi All,

We've stumbled across some build failures in Pybind after implementing support for char8_t under /std:c++latest in the development version of Visual C++. Could you help look at this? Thanks in advance! Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior. 

**Repro steps:**

1. git clone https://github.com/pybind/pybind11 D:\Pybind11\src
2. open a VS 2017 amd64 command prompt as admin and browse to D:\Pybind11
3. set CL=/std:c++latest
4. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src\

**Failures:**
test_builtin_casters.i
D:\Pybind\src\tests\test_builtin_casters.cpp(33): error C2440: '<function-style-cast>': cannot convert from 'const char8_t [22]' to 'std::string'
D:\Pybind\src\tests\test_builtin_casters.cpp(33): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\Pybind\src\tests\test_builtin_casters.cpp(72): error C2440: '<function-style-cast>': cannot convert from 'const char8_t [17]' to 'std::string_view'
D:\Pybind\src\tests\test_builtin_casters.cpp(72): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by YannickJadoul** [comment]
This is VS 2017, compiling a C++ standard dating 3 years later than the compiler. Does this still happen with the latest MSVC version of VS 2019? If so, please reopen.

**Comment by tahonermann** [comment]
@YannickJadoul, this issue is due to changes in C++20.  It is not dependent on the compiler version.

**Comment by henryiii** [comment]
We test C++20 on MSVC 2019, GCC 10, and Clang 10. 2.6.0 compiles correctly and passes all tests. Though does "latest" in 2017 really mean 20? I don't think we try latest on MSVC 2017, though we do run 17 on 2017 in ci.

I'd be surprised if 2.6.0 or master has an issue. But I've been surprised before.

**Comment by bstaletic** [comment]
In this case MSVC 2017 passes the preprocessor test that says

>     #if defined(__cpp_lib_char8_t) && __cpp_lib_char8_t >= 201811L

and then it complains that it doesn't know what `char8_t` is... MSVC 2017 is simply lying. I can't see how this could be a pybin11 bug.

Not to mention that a compiler from 2017 is defining a macro with the value `201811L`.

**Comment by tahonermann** [comment]
> Not to mention that a compiler from 2017 is defining a macro with the value 201811L.

Visual Studio 2017 versions 15.6 and above were released in 2018 or later.

Playing on godbolt.org, I didn't find a version of Visual Studio 2017 that defines either `__cpp_char8_t` or `__cpp_lib_char8_t`.  The VS 2017 versions available on godbolt.org correspond to 15.7 (19.14), 15.8 (19.15), and 15.9 (19.16).  This suggests that this issue report is erroneous in claiming use of VS 2017.

However, the issue summary also states, "Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior".  It sounds like @QuellaZhang was testing with a different compiler release.

As far as I can tell, VS 2019 16.2 (version 19.22 on godbolt.org) is required for `char8_t` support.  Neither `__cpp_char8_t` nor `__cpp_lib_char8_t` appear to be defined in earlier releases.  This matches [Microsoft's documentation](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019).  This version was released in July of 2019, a few months after this issue was created.

If testing succeeds with VS 2019 16.2 or later using `/std:c++latest`, then it seems this issue was already addressed.

**Comment by YannickJadoul** [comment]
> However, the issue summary also states, "Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior". It sounds like @QuellaZhang was testing with a different compiler release.

Well, it's 1.5 years later, so I don't think we need to worry about it, if you cannot fine VS 2017 defining that :-) Thanks a lot for trying out some stuff and getting to the bottom of this, though, @tahonermann!!

I suggest we just forget about this until someone comes complaining again and we get a reproducible issue?

We basically have the same issue with VS 2015, btw, where it's not compiling C++17 correctly (unless `/permissive-` is passed). Even though VS gets updates (so could in principle support later standards), it seems later standards are still kind of problematic for earlier versions of VS?

**Comment by tahonermann** [comment]
> We basically have the same issue with VS 2015, btw, where it's not compiling C++17 correctly (unless /permissive- is passed). Even though VS gets updates (so could in principle support later standards), it seems later standards are still kind of problematic for earlier versions of VS?

I would expect so.  The approach these days is to use standard predefined macros to condition a code base for the features that are available and enabled.  But Microsoft didn't adopt those until they were adopted for C++20.
