### ISSUE TITLE
py::nodelete not work as expected

### ISSUE THREAD

**Issue by twmht** [pybind/pybind11#1796]
I have a parent class having protected destructor.

```
class Foo {
  public:
    Foo() {
      std::cout << "foo" << std::endl;
    }
  protected:
    virtual ~Foo() {
      std::cout << "dfoo" << std::endl;
    }
};

class CFoo: public Foo {
  public:
    CFoo() {
      std::cout << "Cfoo" << std::endl;
    }
  ~CFoo() {std::cout << "dCfoo" << std::endl;}
};

const Foo*  get() {
  return new CFoo;
}
```

as the document suggests, I use `py::nodelete` to destroy the object in c++ side.

for example,

```
 py::class_<Foo, std::unique_ptr<Foo, py::nodelete>> foo(m, "foo");
 m.def("get_foo", &get);
```

in python side,

```
foo=get_foo()
del foo
```

this works as expected, sine the output is 

```
Cfoo
foo
```

However, when I add another def for CFoo

```
py::class_<CFoo> cfoo(m, "cfoo");
```

then the output is not expected.

```
foo
Cfoo
dCfoo
dfoo
```

the expected output is 

```
foo
Cfoo
```

I am not sure if this is the normal behavior or a bug.

any idea?

**Comment by lonestarr** [comment]
you have to specify the base class, and add the same holder type than in that base class: 
`     py::class_<CFoo, std::unique_ptr<CFoo, py::nodelete>, Foo> cfoo(m, "cfoo");`

**Comment by YannickJadoul** [comment]
Thanks for answering, @lonestarr!

This is indeed pure C++ behavior: on instantiation of `py::class_<CFoo> cfoo(m, "cfoo");`, the base class will be constructed, and since you're not specifying to not delete this type of object, C++ will call the destructor of `CFoo` and from there call the `Foo` base class destructor from `~CFoo`.

@lonestarr Perfectly described how to correctly deal with this.
