### ISSUE TITLE
Convention for binding classes and function

### ISSUE THREAD

**Issue by briankosw** [pybind/pybind11#1850]
Hi everyone, what's the convention for binding classes and functions? For example, let's say I have a `example.hpp` and `example.cpp` with a class `Example` and various methods within the class. Where would I put the PYBIND11_MODULE macro? Would it belong in the cpp or hpp file? Or would it live in a separate `binding.cpp` file? I tried to look at PyTorch uses pybind11, but it doesn't seem to invoke the macro in each file.

**Comment by YannickJadoul** [comment]
First of all: not in a header file (since the macro will define a function).
Next, it depends on the purpose of your project/library. I'd argue that keeping the bindings and the main code separate might (often) be a good idea.

Apart from that: consider this `PYBIND11_MODULE` a bit as the `main` of a normal C++ program. It's invoked when you first import the module, and if there's functionality in other functions/translation units, it should be invoked from inside the body of the `PYBIND11_MODULE`.

**Comment by briankosw** [comment]
So then if you have a bunch of different modules in the src directory at different levels, how would you organize the binding code?

**Comment by YannickJadoul** [comment]
@briankosw Have you looked at `def_submodule` and https://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules?

**Comment by bstaletic** [comment]
No further reply to @YannickJadoul's question. Closing.
