### ISSUE TITLE
random access to vector < shared_ptr > deletes vector's element

### ISSUE THREAD

**Issue by amastrobera** [pybind/pybind11#1864]
Dear Pybind, 

I have a class containing an *std::vector<std::shared_ptr<Elem>>*, which I would expect to be converted to python *list(Elem)* objects. Apparently as soon as I access the list, I lose the handle on the original list (it's like python has "moved" it instead of copying it). I also get "double free" error once the program terminates. **can you help me?**

**--- error from python console ---**
```
$ python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from dynamic_type import Container, Elem, Deriv1, Deriv2
>>> c = Container()
>>> d1 = Deriv1()
>>> d1.talk()
i am derived 1
>>> d2 = Deriv2()
>>> d2.talk()
i am derived 2
>>> c.addElem(d1)
>>> c.addElem(d2)
>>> len(c.elems)
2
>>> len(c.elems)
2
>>> c.elems
[None, None]
>>> d1.talk()
i am derived 1
>>> d2.talk()
i am derived 2
>>> del c.elems
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't delete attribute
>>> del c.elems[0]
>>> del c.elems[0]
>>> len(c.elems)
2
>>> c.elems
[None, None]
>>> c.elems.append(d1)
>>> len(c.elems)
2
>>> c.elems
[None, None]
>>> c.elems[0]
>>> c.elems[0].talk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'talk'
>>> c.elems
[None, None]
>>> c.addElem(d1)
>>> c.elems
[None, None, None]
```

--- main.cpp ---
```
#include <iostream>                           
#include <vector>
#include <memory>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;          

                               
                                      
class Elem {
public:
    virtual ~Elem() = default;
    void talk() { std::cout << "i am " << type() << std::endl; }
protected:
    virtual std::string type() = 0;
};

class Deriv1 : public Elem {
protected:
    std::string type() override { return "derived 1"; }
};

class Deriv2 final : public Deriv1 {
protected:
    std::string type() override { return "derived 2"; }
};

class Container {
public:

    std::vector<std::shared_ptr<Elem>> const& getElems() const { return mElems;}
    std::vector<std::shared_ptr<Elem>>& getElems() { return mElems;}

    void addElem(Deriv1 const& val) { mElems.push_back(std::shared_ptr<Elem>(new Deriv1(val)));}
    void addElem(Deriv2 const& val) { mElems.push_back(std::shared_ptr<Elem>(new Deriv2(val)));}

private:
    std::vector<std::shared_ptr<Elem>> mElems;

PYBIND11_MODULE(dynamic_type, m) {

    py::class_<Elem>(m, "Elem")
          .def("talk",  & Elem::talk);

    py::class_<Deriv1, Elem>(m, "Deriv1")
          .def(py::init<>());

    py::class_<Deriv2, Deriv1>(m, "Deriv2")
          .def(py::init<>());

    py::class_<Container>(m, "Container")
          .def(py::init<>())
          .def_property("elems", (
                  std::vector<std::shared_ptr<Elem>> const& (
                                           Container::*)() const) & Container::getElems,
                        (std::vector<std::shared_ptr<Elem>> & (
                                             Container::*)()) & Container::getElems)
          .def("addElem", (void (Container::*)(Deriv1 const&)) & Container::addElem)
          .def("addElem", (void (Container::*)(Deriv2 const&)) & Container::addElem);

}


//// compiles with a simple $ g++ -I. main.cpp
//// runs with a simple $ ./a.out
//int main() {
//
//    Container c;
//    c.addElem(Deriv1());
//    c.addElem(Deriv2());
//
//
//    for (auto it : c.getElems())
//        it->talk();
//
//    return 0;
//}

```

I attach the file with my example 
[dynamic_type.zip](https://github.com/pybind/pybind11/files/3453130/dynamic_type.zip)

**Comment by amastrobera** [comment]
@YannickJadoul do you know how to do by any chance ?

**Comment by YannickJadoul** [comment]
@amastrobera I believe your holder types and/or return value policy are to blame: you're returning a vector of (smart) pointers, without return value policy. So, the default return value policy will kick in, which is taking ownership of returned pointers. Since you haven't specified a special holder type for `Elem`, `Deriv1`, and `Deriv2`, pybind11 will create unique_ptrs taking ownership of your returned pointers. This results in two smart poiners owning the memory. BOOM.
(I'm not entirely sure why the element becomes `None`, but I'm sure it's related.)

There are two things you can do to solve this:
1) You can specify holder types (i.e., `py::class_<Elem, std::shared_ptr<Elem>>`, `py::class_<Deriv1, std::shared_ptr<Deriv1>, Elem>`, `py::class_<Deriv2, std::shared_ptr<Deriv2>, Deriv1>`). Now all Python objects of this type will have a `std::shared_ptr` inside of them, meaning they will share ownership nicely. Extra advantage: you can just have `void addElem(std::shared_ptr<Elem> val) { mElems.push_back(std::move(val)); }`. No need to copy anymore and no need for overloads of different derived types.
2) I thínk (but I'm not entirely sure; just give it a try) you can probably specify `py::return_value_policy::reference` for that `def_property`, and stop the Python object from taking ownership of the pointer. You do need to keep that `Container` alive as long as you keep accessing the elements, in that case, since their Python objects don't share ownership.

Independently from that: it seems you have a weird setter for your property. Does this work? I thought you needed a function that takes the new value?

**Comment by amastrobera** [comment]
**omfg. yes number 1 works**. I suspected that was the issue ... it's the only thing i didn't test. 

I had tried `keep_alive<1,2>` inside `addElems` previously, and also `return_value_policy::reference` but nothing. 

So, thanks a lot.
