### ISSUE TITLE
Recommended way to debug pybind11

### ISSUE THREAD

**Issue by rfsch** [pybind/pybind11#1931]
Hello
I am trying to debug pybind11 applications on Linux Ubuntu. Maybe this is a bit off topic. But I would be grateful for recommending the best way. We are using Clion, Qtcreator and Pycharm. 

Thank you

**Comment by YannickJadoul** [comment]
What and how exactly do you want to debug?
You should just be able to debug this in your favorite debugger (gdb, lldb, ...), by starting Python in there, and importing your extension. And embedded application should be even more straightforward.

There are also debug builds of Python that allow you to get a detailed stack trace if something goes wrong inside of the Python interpreter (found in the `python-dbg` package on Debian/Ubuntu), rather than in your extension code. I've never needed, that, though.

Apart from that, pybind11 isn't any different from other Python C API uses. So have a look [here](https://pythonextensionpatterns.readthedocs.io/en/latest/debugging/debug_in_ide.html) or [here](http://droettboom.com/blog/2015/11/20/gdb-python-extensions/).

Also, it can be easier to come ask such questions on [Gitter](http://droettboom.com/blog/2015/11/20/gdb-python-extensions/).

**Comment by kyrlon** [comment]
If you use VS Code, you can either attach a process or launch with GDB in the debugger as mentioned from this SO post
https://stackoverflow.com/questions/61490100/debugging-pybind11-extension-with-visual-studio-code-macos

**Comment by YannickJadoul** [comment]
Thanks for the addition, @kyrlon!

**Comment by Geremia** [comment]
@YannickJadoul 

> You should just be able to debug this in your favorite debugger (gdb, lldb, ...), by starting Python in there

Abiding by the [KISS principle](https://www.gutenberg.org/cache/epub/3008/pg3008-images.html#KISSPrinciple). 👍 **But** `python` isn't usually compiled with debugging symbols.

What if you use `pytest`, too? For example, attaching a debugger to:
```
python -m pytest test.py
```
doesn't work, even if the C++ code that `pybind` runs was compiled with debugging symbols (GCC `-g`).
