### ISSUE TITLE
arg_v: description omits default value

### ISSUE THREAD

**Issue by ax3l** [pybind/pybind11#1955]
## Issue description

The generated documentation/signature of `pybind11::arg_v` has the following problematic behaviour:

The overload
```C++
pybind::arg_v("bool_argument", true)
```
is properly presented as
```
The following argument types are supported:
1. (bool_argument: bool = True) -> None
```

But if we now add a description such as
```C++
pybind::arg_v("bool_argument", true, "This is my description")
```
the doc string show up as
```
The following argument types are supported:
1. (bool_argument: bool = This is my description.) -> None
```
the default argument (`True`) is now missing!

I would instead expect something like
```
The following argument types are supported:
1. (bool_argument: bool = True; This is my description.) -> None
```

## Reproducible example code

See above, e.g. in
```C++
#include <pybind11/pybind11.h>
namespace py = pybind11;

PYBIND11_MODULE(my_module, m) {
    m.def("foo",
        [](bool const bool_argument = false) {
           return;
        },
        py::arg_v("bool_argument", false, "This is my description."),
        "My general description"
    );
}
```

Compiled with `g++` 7.4.0, `-std=c++14` (other flags: `-Wall -Wextra -O3 -DNDEBUG -fPIC -fvisibility=hidden   -std=c++14 -flto -fno-fat-lto-objects`) and pybind11 v2.3.0.

**Comment by YannickJadoul** [comment]
I'd love to see pybind11 support argument descriptions and insert them into docstrings, but as far as I know, `arg_v` was created to specify a custom type annotation into the signature (if the auto-generated is for some reason not good enough), rather than to document the argument.

Once the cleanup is closer to ready, this might be one of the things to think about, though! :-)
