### ISSUE TITLE
 boost.string_view support

### ISSUE THREAD

**Issue by kotbegemot** [pybind/pybind11#1980]
How to make boost.string_view support ?

**Comment by kotbegemot** [comment]
How to support the boost.string_view on the side of the project ? @

**Comment by kotbegemot** [comment]
help please @wjakob

**Comment by YannickJadoul** [comment]
Since this is used for `std::string_view`:

https://github.com/pybind/pybind11/blob/0d70f0e18eec60786499faba53de4d72583ba2f7/include/pybind11/cast.h#L1310-L1314

adding something to your code like

```c++
namespace pybind11 {
namespace detail {
template <typename CharT, class Traits>
struct type_caster<boost::basic_string_view<CharT, Traits>, enable_if_t<is_std_char_type<CharT>::value>>
    : string_caster<boost::basic_string_view<CharT, Traits>, true> {};
} // namespace detail
} // namespace pybind11
```

might also work?

Please give it a try (or use `std::string_view`, if you can), and reopen this issue if that doesn't solve it.
