### ISSUE TITLE
object_api: is there a way to call with an py::object array

### ISSUE THREAD

**Issue by yorkie** [pybind/pybind11#2012]
##  Issue description

This is a feature request, see the following firstly:

```cpp
template <typename Derived>
template <return_value_policy policy, typename... Args>
object object_api<Derived>::operator()(Args &&...args) const {
    return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());
}
```

I'm embedding the pybind11, and occurs some cases that we have dynamical array that might be passed to the above operator function, unfortunately pybind11 seems only supports to pass the parameters pack, how about adding another way:

```cpp
template <typename Derived>
template <return_value_policy policy, std::array<object, size_t>>
object object_api<Derived>::operator()(std::array<object, size_t> args) const {
  // TODO
}
```

This might be useful for some dynamical and bypass use cases.

**Comment by eacousineau** [comment]
If I understand your question correctly, you can already do this:
https://pybind11.readthedocs.io/en/stable/advanced/pycpp/object.html#unpacking-arguments
(I believe this policy is achieved through a combo of `object_api::operator*` and `collect_arguments`, which will then dispatch to `detail::unpacking_collector`.)

You have to construct your arguments using `py::list` or `py::dict` which is slightly less efficiently than going straight from `std::array` to an argument pack, but it probably won't be a super huge performance impact for moderate use cases.

Also, overloading `operator()` for `std::array` will not be backwards compatible (since it is ambiguous for single-argument functions that take `std::array`), so you would need to make a special tag type (like `py::arg` or `py::kwargs`).

**Comment by YannickJadoul** [comment]
Thanks @eacousineau! Closing, as there's no further reaction to this answer.
