### ISSUE TITLE
proper way to cast std::vector<std::array<double, 3>> to numpy.array

### ISSUE THREAD

**Issue by T4mmi** [pybind/pybind11#2066]
Hi all,

Briefly, I'm trying to expose C++ a vector of points coordinates in Python using pybind11.

*I'm using CGAL for heavy lifting meshes \*stuff\*,  and managed to extract resulting vertices and facets vectors. I'm looking for a way to cast them into py::array to use them in the interpreter for scripting purposes*
```
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
namespace py = pybind11;

auto to_arrays(const C2t3& c2t3) {
    using Vertex = std::array<double, 3>;
    using Facet = std::array<std::size_t, 3>;
    auto tr = c2t3.triangulation();
    std::vector<Vertex> vertices(tr.number_of_vertices()); // vertices indexes
    std::vector<Facet> facets(c2t3.number_of_facets()); // facets indexes
    [...] //  vectors filling stuff (working, can display all elements)
    return py::make_tuple(
        py::array(py::cast(vertices)),
        py::array(py::cast(facets))
    );
```

Everything compiles fine, but I got a `ValueError: cannot create a pybind11::array from a nullptr` at runtime ...

**What is the proper way to expose such *hybrids* vectors to python?**
*if possible without copying them since we are talking about LARGE amounts of points/facets ...*

**Comment by wjakob** [comment]
You need to include stl.h, please read the documentation :)

**Comment by T4mmi** [comment]
Thanks, the `#include <pybind11/stl.h>` did the trick ...  
*might help someone else in the futur...*

sorry to say, but witch documentation ? `py::array(py::cast(T))` doesn't even appear in the [doc](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#arrays)  
[edit] partial answer could be found in the STL [containers section](https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#automatic-conversion), might be a nice suggestion to reference it inside the array section and add the macro `py::array(py::cast(T))` ;)

**Comment by wjakob** [comment]
Please feel free to submit a PR.

**Comment by mglisse** [comment]
Since I was led here by a google search, others might arrive here as well, so let me mention that `py::array(py::cast(vec))` is not such a great idea. From what I can see, it first creates a python list of python tuple of python float, before creating a numpy array from that. A lot of unnecessary work.

**Comment by YannickJadoul** [comment]
@mglisse Yes, indeed. If you split it into two parts, things become clear: `py::cast(vec)` casts a `vector<std::array<...>>` to Python. If you use `stl.h`, it gets copied (as described in the docs). So at that point, you have a Python object (a `list`, to be precise), and `py::array(...)` will just construct a NumPy array from that. If you consider these independently, everything makes sense.

It's definitely the easiest way, as pybind11 takes care of everything (i.e., you don't need to think about keeping C++ memory alive in Python), but you do pay a performance price for that simplicity (as is so often the case).

**Comment by mglisse** [comment]
To be fair, almost the same code, `py::array(py::cast(std::move(vec)))`, can be rather efficient, if you have suitable `PYBIND11_MAKE_OPAQUE(V);` and `py::bind_vector<V>(m, "VectorArrayDouble3", py::buffer_protocol());` before, it has the overhead of an extra python object, but doesn't seem to copy the data at all.

**Comment by YannickJadoul** [comment]
@mglisse OK, yes, that will steal the `std::vector` into an `std::vector` inside a Python object, and because it supports the buffer protocol, it doesn't get copied. Though it looks similar, we're talking about a very different route to get to a NumPy array, though, but yes, it's a very interesting solution! Nice solution! :-)

At any rate, the separation into two steps stays there: `py::cast` could copy or not (depending on whether it becomes its own type or a Python `list`), and `py::array` could copy or not (depending on whether there's a Python buffer-protocol-supporting object it can keep alive or whether it needs to copy). At any rate, I'd argue to not consider `py::array(py::cast(...))` an idiom; interpreting it as two independent steps will make things a lot clearer.
