### ISSUE TITLE
pybind11::pickle is called on an uninitialized instance.

### ISSUE THREAD

**Issue by fbriol** [pybind/pybind11#2148]
The test module has the following rudimentary class:

```cpp
#include <pybind11/pybind11.h>
#include <iostream>

namespace py = pybind11;

PYBIND11_MODULE(pickling, m) {
  class Pickleable {
   public:
    Pickleable() {
      std::cout << "create " << static_cast<void *>(this) << std::endl;
    };
    ~Pickleable() {
      std::cout << "destroy " << static_cast<void *>(this) << std::endl;
    }
  };

  py::class_<Pickleable>(m, "Pickleable")
      .def(py::init<>())
      .def(py::pickle([](const Pickleable &p) { return py::make_tuple(); },
                      [](py::tuple t) {
                        if (t.size() != 0)
                          throw std::runtime_error("Invalid state!");
                        auto p = Pickleable();
                        return p;
                      }));
}
```

Then we execute the following Python code.

```python
In [1]: import pickle                                                                                      
In [2]: import pickling                                                                                    
In [3]: h=pickling.Pickleable()                                                                            
create 0x7fd89406b540
In [4]: h2=pickle.loads(pickle.dumps(h))                                                                   
create 0x7ffeefbc8530
destroy 0x7ffeefbc8530
In [5]: del h, h2                                                                                          
destroy 0x7fd89406b540
destroy 0x7fd891e860b0
```
The destructor is called three times for two different instances. If the function building the new class is modified in this way, the destructor is called only twice. 

```cpp
      .def(py::pickle([](const Pickleable &p) { return py::make_tuple(); },
                      [](py::tuple t) {
                        if (t.size() != 0)
                          throw std::runtime_error("Invalid state!");
                        auto p = new Pickleable();
                        return p;
                      }));
```
The problem is the class copies. Perhaps the user should be warned that in this scenario, the destructor may call more than once. Indeed, if a shared pointer is used to handle the class, the problem disappears.

**Comment by bstaletic** [comment]
> The destructor is called three times for two different instances. 

No, the destructor is called 3 times for 3 instances.

- `h` is a reference to the one that is default constructed. This is the first `create 0xDEADBEEF`
- `auto p = Pickleable();` is the second instance. This is the second `create 0x7fwhatever`. The `0x7f` is usually a dead giveaway that this is on the stack. Not in your case, because you were likely close to running out of memory when you ran your example code.
- `return p` returns by copy, creating a 3rd instance. This uses a move constructor. One for which you don't have a `cout` statement.

Now for the destructors.

- First you destroy the one on the stack, which is the immediately repeated `0x7fwhatever`, but now with `destroy.
  - At this point you still have two instances on the heap.
- Then you run `del h, h2` and destroy the other two on the heap, printing `destroy 0xDEADBEEF` and `destroy 0xCAFEBABE`.

If you add something like `Pickleable(Pickleable&&) { std::cout << "create " << this << '\n'; }` then the output would look something like this:

```
>>> import pickle
>>> import xxx
>>> h = xxx.Pickleable()
create 0x55f6df904fa0
>>> h2 = pickle.loads(pickle.dumps(h))
create 0x7ffd0d7f863f
create 0x55f6df905120
destroy 0x7ffd0d7f863f
>>> del h, h2
destroy 0x55f6df904fa0
destroy 0x55f6df905120
```

Like I said, 3 constructors and 3 destructors including a constructor-destructor pair on the stack.

Now with `auto p = new Pickleable();` this happens:

- `h = Pickleable()` allocates an instance. This is `create 0xDEADBEEF`
- `auto p = new Pickleable();` creates a second instance on the heap. This is `create 0xCAFEBABE`.
  - The returned pointer is adopted by the holder class, so there's no copying.
- Then comes `del h, h2` which invokes the two destructors and we get `destroy 0xDEADBEEF` and `destroy 0xCAFEBABE`.

&nbsp;

I don't see a bug here, only C++ being C++. Feel free to reopen if I've missed something.
