### ISSUE TITLE
Custom excepthook in embeded python code

### ISSUE THREAD

**Issue by LinasBeres** [pybind/pybind11#2174]
Hi, I have a custom sys.excepthook in some python code that I am running, which doesn't seem to be working when I run it through embeding the python interpreter. Is there any way for me to make this work?

**Comment by pranav-vempati** [comment]
Can you provide a minimal and complete example?

**Comment by YannickJadoul** [comment]
> Can you provide a minimal and complete example?

Yes. Without this, we can't do much. I'm guessing you expect `sys.excepthook` to be called when an error occurs in `py::exec` or `py::eval`?

But the Python docs on `sys.excepthook` specify that:

> When an exception is raised and uncaught, the interpreter calls sys.excepthook with three arguments, the exception class, exception instance, and a traceback object. In an interactive session this happens just before control is returned to the prompt; in a Python program this happens just before the program exits.

So it seems that this is really the last thing the interpreter/main interpreter fall back. On the other hand, embedding the interpreter through the C API (and the same for pybind11), an error code is returned and the error is set, because potentially the embedding program wants to handle the error, rather than have Python just print a stack trace.

So I don't think `sys.excepthook` is expected to be called in such case, and you'll have to do it yourself. The good news is, it's really not that hard:

```c++
#include <pybind11/embed.h>

namespace py = pybind11;

int main(int argc, char **argv)
{
    py::scoped_interpreter guard{};
    try {
        py::exec("import sys\nsys.excepthook = print");
        py::print(py::eval("1 + 1"));
        py::print(py::eval("1 + 'x'"));
    }
    catch (const py::error_already_set &e) {
        py::module::import("sys").attr("excepthook")(e.type(), e.value(), e.trace());
    }
}
```
