### ISSUE TITLE
make_iterator question.

### ISSUE THREAD

**Issue by aractnido** [pybind/pybind11#2194]
I'm getting in VC++:

C2027: use of undefined type 'pybind11::detail::process_attribute<std::shared_ptr<IEnumerable<T>>,void>'

When doing:
```
py::iterator CreatePyIter(unique_ptr<IEnumerable> enumerable)
{
    auto begin = enumerable.cbegin();
    auto end = enumerable.cend();
    // Move the enumerable inside the iterator.
    shared_ptr<IEnumerable<T>> keepAlive(enumerable.release());
    return py::make_iterator</*pybind11::return_value_policy::??*/>(begin, end, move(keepAlive));
}
```
'begin' and 'end' are just iterators that use a raw pointer. The enumerable parameter is originally allocated as unique ptr and then I try to tell make_iterator that it can own it. It could own it as a unique_ptr or shared_ptr, either way would be fine.

1. What is this error about? Do I need to declare IEnumerable before pybind11 headers?
2. What is the right policy? Ideally I would like to forget about the IEnumerable object and let the caller of 'CreatePyIter' own it. Ideally too, I would like avoid the object to be kept alive longer than the current thread's lifetime (there is a special thread_local allocator).

Thank you so much.

**Comment by YannickJadoul** [comment]
The error says that pybind11 has no clue what to do with the `move(keepAlive)`. You probably need/want to choose some kind of `return_value_policy` when returning the `py::iterator` back to Python, in your call to `def`?

PS: There's [Gitter](https://gitter.im/pybind/Lobby) if you want a quick answer to a question, rather than actually reporting an issue with pybind11.
