### ISSUE TITLE
pybind11 created method does not work with `inspect.ismethod(method)` nor isinstance(method, types.MethodType)

### ISSUE THREAD

**Issue by xush6528** [pybind/pybind11#2262]
```py

method = MyPyBindClass.some_method

print(type(method))
# <class 'instancemethod'>

import inspect
print(inspect.ismethod(method))
# False

import types
print(isinstance(method, types.MethodType))
# False
```

**Comment by chaitan94** [comment]
I am not exactly sure why this is, but I think this might be the expected behavior.
Here's an example which doesn't even involve pybind:

```python
class Foo(object):
    def bar(self):
        return "baaz"

method = Foo.bar
print(type(method))

import inspect
print(inspect.ismethod(method))

import types
print(isinstance(method, types.MethodType))
```

The output I get:
```
<class 'function'>
False
False
```

Maybe this explains at least a part of why this might be the behavior: https://wiki.python.org/moin/FromFunctionToMethod

**Comment by chaitan94** [comment]
After some more experimenting, it seems behavior is different when I run the same script using python 2.7. This is the output I get with py2.7:
```
<type 'instancemethod'>
True
True
```

**Comment by xush6528** [comment]
Thanks. I think Python3 changed this behavior.

```py
a = Foo()

method = a.bar
print(type(method))

import inspect
print(inspect.ismethod(method))

import types
print(isinstance(method, types.MethodType))
```

```
<class 'method'>
True
True
```

**Comment by xush6528** [comment]
Let me re-phraze the issue. 


The issue is for Python3.

```
print(type(Foo.bar))
# <class 'function'>
```

While if `Foo` is a pybind11 generated class.
```
print(type(Foo.bar))
# <class 'instancemethod'>
```

Let me know if this warrants another issue.

**Comment by YannickJadoul** [comment]
Apart from the whole bound vs. unbound, and Python 2 vs. 3 differences, this is just a result of having a C extension and methods in there. There are a bunch of different method/function types, and they end up different from exposed C functions than for pure Python ones, just because of CPython implementation details.

For example, the built-in `str.join` from Python's standard acts differently as well, and is even still different from pybind11:

```pycon
>>> import inspect, types
>>> inspect.ismethod(str.join)
False
>>> isinstance(str.join, types.MethodType)
False
>>> type(str.join)
<class 'method_descriptor'>
>>> inspect.ismethod(''.join)
False
>>> isinstance(''.join, types.MethodType)
False
>>> type(''.join)
<class 'builtin_function_or_method'>
```

This is not something that's easily fixed, would require a whole rework of pybind11 (if possible at all, to fix it), and would probably be less efficient than the current one.

I'd say: don't worry about it, if it also happens in the Python builtins/standard library, since things just work, and you can call these methods as you would call any method. Python loves a bit of duck-typing anyway.
