### ISSUE TITLE
C++ Class Object Method Numpy Array Argument Example

### ISSUE THREAD

**Issue by benjamincommeau2** [pybind/pybind11#2274]
Is there any example code of a C++ class object having a method that accepts an argument that is a numpy array? I have been only able to verify that C++ scripts containing a module of methods works, but class objects with methods do not work for me.

- Below is my C++ class object taken and modified from a C++ Method Module example.

```
<%
cfg['compiler_args'] = ['-std=c++17']
setup_pybind11(cfg)
%>

#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>

namespace py = pybind11;


class mine{
private:
public:
  mine(){};
// Passing in a generic array
double sum(py::array xs) {
    py::buffer_info info = xs.request();
    auto ptr = static_cast<double *>(info.ptr);

    int n = 1;
    for (auto r: info.shape) {
      n *= r;
    }

    double s = 0.0;
    for (int i = 0; i <n; i++) {
        s += *ptr++;
    }

    return s;
}
};

PYBIND11_MODULE(code,m) {
    pybind11::class_<mine>(m,"mine")
    .def(py::init<>())
    .def("sum", &mine::sum)
;
    //return m.ptr();
}
```

- Below is my python test code

```
import cppimport
import numpy as np

code0 = cppimport.imp("code")
code=code0.mine


if __name__ == '__main__':
    xs = np.arange(12).reshape(3,4).astype('float')
    print(type(xs[0,0]))
    print(xs.flags)
    print("np :", xs.sum())
    print("cpp:", code.sum(xs))
```

- Below is my terminal output

```
<class 'numpy.float64'>
C_CONTIGUOUS : True
F_CONTIGUOUS : False
OWNDATA : True
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
UPDATEIFCOPY : False
np : 66.0
Traceback (most recent call last):
File "code.py", line 13, in <module>
print("cpp:", code.sum(xs))
TypeError: sum(): incompatible function arguments. The following argument types are supported:
1. (self: code.mine, arg0: array) -> float
Invoked with: array([[ 0.,  1.,  2.,  3.],
                     [ 4.,  5.,  6.,  7.],
                     [ 8.,  9., 10., 11.]])
```

EDIT (@YannickJadoul): Cleaned up formatting. Please use ``` to quote multiline code blocks.

**Comment by YannickJadoul** [comment]
The problem is not related to numpy arrays: free functions and methods work exactly the same for argument casting.
The problem is that `code = code0.mine` is a type, and not an instance. So you can't call a non-static method on a type, and that's what the error is complaining about.

Btw: please clean up your formatting next time you report an error; it's important so we can immediately see what's going on and don't waste time. Also, for these kinds of questions that are not really pybind11 issues, there's [Gitter](https://gitter.im/pybind/Lobby).
