### ISSUE TITLE
Error extending with Python 3.5

### ISSUE THREAD

**Issue by amorenoher** [pybind/pybind11#228]
Hi,

I'm pleased with how pybind11 works with Python 2.7.11 but I'm struggling to get the same code to work with Python 3.5.1. Python is not loading the module.

Am I missing something?

I have raised this question on stackoverflow with the details.
http://stackoverflow.com/questions/37654018/error-extending-and-embedding-python-3-5-with-pybind11

Thank you very much in advance.
Alex

**Comment by wjakob** [comment]
Running the interpreter from the C++ side is not an officially supported feature, so I fear that you are on your own. That said, I would be curious to know why it fails if you do find out.

**Comment by GeorgViehoever** [comment]
Is there any specific reason why running the interpreter from the C++ side might be difficult? I would think that running it from C++ is not so different from running it by starting the main() function in Python's normal operation.

For me, this would be an interesting use case.

**Comment by wjakob** [comment]
I don't think it's inherently difficult. It's just that my resources (mainly time) for supporting every kind of use case are limited. I'd be happy to make it an official feature if others spend the time/submit PRs to fix all the involved issues and expose it via a C++ API.

**Comment by bennybp** [comment]
I got curious also, since I may be interested in this in the future.

It looks like the importing is different in python3 than python2. In python3, you have to use `PyImport_AppendInittab` to register the init function for the module, and the import machinery will use the given info.

Unfortunately, it requires a C function pointer that returns a `PyObject *` for the module, which isn't really compatible with C++. You need a plain C function (not a class member function, not `std::bind`, etc) that takes no arguments and will return the new module. Since it takes no arguments (that could be used to differentiate between different modules), you are basically restricted to hard-coding it yourself for each module.

This is the best I can think of. There are probably other ways, but I'm not too familiar with python internals.

    #include <pybind11/pybind11.h>
    namespace py = pybind11;

    const char * world() { return "Hello world!"; }

    // Looks a lot like a normal pybind11 export function...
    PyObject * InitHello(void)
    {
        py::module m("hello", "my hello world Python module with pybind11");
        m.def("world", &world);

        // Not positive if incrementing is required
        return m.ptr();
    }

    int main(int argc, char ** argv)
    {
        PyImport_AppendInittab("hello", &InitHello);
        Py_Initialize();
        PyRun_SimpleString("import hello\nprint( hello.world() )");
        Py_Finalize();
    
        return 0;
    }

See: https://docs.python.org/3/c-api/import.html#c.PyImport_AppendInittab and http://bugs.python.org/issue4592
