### ISSUE TITLE
  CMake's 'find_host_package(PythonInterp 2.7)' founds wrong Python version:

### ISSUE THREAD

**Issue by yaoganxingwei** [pybind/pybind11#2386]
CMake Warning at cmake/OpenCVDetectPython.cmake:81 (message):
  CMake's 'find_host_package(PythonInterp 2.7)' founds wrong Python version:

  PYTHON_EXECUTABLE=D:/Program Files/python/python.exe

  PYTHON_VERSION_STRING=3.8.1

  Consider specify 'PYTHON2_EXECUTABLE' variable via CMake command line or
  environment variables

Call Stack (most recent call first):
  cmake/OpenCVDetectPython.cmake:271 (find_python)
  CMakeLists.txt:595 (include)

**Comment by YannickJadoul** [comment]
Is this related to pybind11? I only see `cmake/OpenCVDetectPython.cmake` in your error message.
Can you give some more details/further explanation/minimal example that reproduces this error?

**Comment by henryiii** [comment]
OpenCV has a _heavily_ modified FindPythonInterp/FindPythonLibs search, just like we do (only more extreme for them). They are very unlikely to be compatible. You can try pybind11 first, and see if OpenCV is happy with that (probably not). Otherwise, wait until #2370 and then use `PYBIND11_NOPYTHON` mode.

**Comment by henryiii** [comment]
PS: `find_host_package` is not a CMake command, it's probably something added by OpenCV.
