### ISSUE TITLE
overload using pybind11

### ISSUE THREAD

**Issue by kaiy13387** [pybind/pybind11#2440]
Hi,
Assume I have two functions in C++
test(string name, int age)
test(string name, string home)

and in pybind11, this looks allowed:
.def("test",py::overload_cast<string,int>,(&test),  py::arg("name"), py::arg("age") = 10)
.def("test",py::overload_cast<string,string>,(&test),  py::arg("name"), py::arg("home") = "myhome")

from python side, when I run: test("hello"), it choose the first one.
should this be an illegal definition? this is not allowed in c++

so, any comment on this?

thanks

**Comment by bstaletic** [comment]
In order to make this illegal pybind would have to introduce a significant amount of overhead. Instead, pybind11 takes exactly what you've given it (in terms of overloads *and* passed arguments) and then calls the first overload it can. Pybind11 doesn't even do the "best match" magic that a C++ compiler does.

The crucial difference is that a C++ compiler has this information at compile time, but pybind11 gets the info only at runtime.

**Comment by YannickJadoul** [comment]
Ideally, yes.
Realistically, implementing this kind of overload resolution is probably too complex, both in development and maintenance as well as in run time.
Practically, it's probably hard to find someone crazy enough to want to implement this.

The fact that the order of overloads is important, as @bstaletic so nicely explained, is also outlined here: https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order

I'll close this. I don't see any "issue" to be fixed, here, particularly as this is documented.

**Comment by kaiy13387** [comment]
Thanks for the explanation
