### ISSUE TITLE
[QUESTION] adding method dynamically

### ISSUE THREAD

**Issue by jpribele** [pybind/pybind11#2464]
I am trying to define a method dynamically from data. 
For discussion sake say I have json data the describes a function.
name, return type, and arguments.

The body of said function would largely be the same for every function invoking a server call marshaling the arguments etc etc.
What I would like to is define a module function described by said data. so that
help(module)
Shows everything it would if the function was defined in code.
int MyFunc(int a, float b){ .... }
m.def("MyFunc", &MyFunc);

In theory I could use the Python Library directly it just looks god awful to do. 
I think its possible to do what I want but I can't find any examples or quite wrap my head around how to use the pybind library to do what I want

**Comment by YannickJadoul** [comment]
>  name, return type, and arguments.

This could potentially be done at runtime, but the actual problem is that you are binding a C/C++ function, which needs to have had its code compiled at compile time. You can't bind any function that isn't compiled. You could of course generate bindings code, but you'd have to generate those each time.

Now, Python is probably a much better fit for this. Maybe you could factor out the C/C++ parts and call them from dynamically generated Python functions?
Otherwise, maybe there are some libraries that would compile pybind11 code on the fly (similar to `cppimport` listed [here](https://pybind11.readthedocs.io/en/stable/compiling.html)).

If I misunderstood, or you can give an example of what you'd like to achieve, do please reopen. But otherwise, I don't think pybind11 has support for this, so I'll close this.
