### ISSUE TITLE
Class method returns object itself

### ISSUE THREAD

**Issue by nafur** [pybind/pybind11#254]
I have roughly the following code:
```cpp
class N {};
class Interval {
  N mLower;
  N mUpper;
public:
  inline const N& lower() { return mLower; }
  inline const N& upper() { return mUpper; }
};
```
```cpp
py::class_<Interval>(m, "Interval")
  .def("lower", &Interval::lower)
  .def("upper", &Interval::upper);
```
Of course, `N` is also known to python and `Interval` has a bunch of other methods.

Now the following happens:
```python
> i = Interval(1,2)
> print(i)
[1,2]
> i.lower()
[1,2]
> i.upper()
2
```
`lower()` seems to return the object itself, not the member it is supposed to. `upper()` however works fine, though everything is implemented analogously.

We have unit tests in place for the C++ side, `Interval::lower()` works fine.

I managed to find a workaround here: using `.def("lower", &Interval::lower, py::return_value_policy::reference_internal)` actually fixes the problem.
Still I'd really like to know what's going on here...
In my understanding, pybind should use `return_value::copy` by default, which should also be fine. (Though it is probably a bit slower...)

**Comment by wjakob** [comment]
You always need ``return_value_policy::reference_internal`` for what you are doing here -- the binding code is invalid as specified above. Because you're not specifying a return value policy, pybind11 activates an optimization which makes no sense in this setting: it checks if the returned address reference already exists as some kind of referenced Python object. Since the address is the same as the ``Interval`` instance, it avoids the cost of casting and directly returns that instance, which doesn't even have the right type. However, the problem is squarely with the binding code here.

**Comment by nafur** [comment]
Okay, thanks!
Did I simply miss this in [the docs](https://pybind11.readthedocs.io/en/latest/advanced.html#return-value-policies) or do the docs fail to mentioned it (yet)?
I'd expect that either references are handled correctly out of the box, or that the docs state that you should use the correct policy, otherwise you may get undefined behaviour.

In this case, according to the docs, `automatic` should be suboptimal (as it induces a copy) but not incorrect...

**Comment by wjakob** [comment]
The docs suggests to read the return value policies carefully and mentions that auto is not always the right policy. PRs which improve the docs are welcomed, if you have concrete suggestions.
