### ISSUE TITLE
[QUESTION] Strage behaviour with overloading

### ISSUE THREAD

**Issue by maugarsb** [pybind/pybind11#2556]
Hello, 

Thx for this useful library. I start wrapping a C++ code to expose multiple algorithm in python.

I try to dispatch to a generic (or not) C++ function depending of the numpy underlying type :

```cpp
#include <iostream>
#include <vector>
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>

namespace py = pybind11;

template<typename g_num>
void auto_dispatch(py::array_t<g_num>& face_vtx, py::array_t<int>& face_vtx_idx){
  std::cout << __PRETTY_FUNCTION__ << std::endl;
  std::cout << "face_vtx.shape()   " << face_vtx.shape()    << std::endl;
  std::cout << "face_vtx.itemsize()" << face_vtx.itemsize() << std::endl;
  std::cout << "face_vtx.size()    " << face_vtx.size()     << std::endl;
}


PYBIND11_MODULE(dispatch, m) {
  m.doc() = "pybind11 dispatch plugin"; // optional module docstring
  m.def("auto_dispatch", &auto_dispatch<int>   , "A test with numpy array");
  m.def("auto_dispatch", &auto_dispatch<long>  , "A test with numpy array");
}
```
My test look likes this : 

```python
def test_automatic_dispatch_pybind():
  """
  """
  from my_lib as ML
  import numpy as NPY

  face_vtx_32  = NPY.empty(10, dtype='int32', order='F')
  face_vtx_64  = NPY.empty(10, dtype='int64', order='F')
  face_vtx_idx = NPY.empty(3 , dtype='int32', order='F')

  face_vtx_u64  = NPY.empty(10, dtype='double', order='F')

  ML.auto_dispatch(face_vtx_32, face_vtx_idx)
  ML.auto_dispatch(face_vtx_64, face_vtx_idx)

  try:
    ML.auto_dispatch(face_vtx_u64, face_vtx_idx)
  except TypeError:
    print("Bad type pass")
    pass
```
But when i pass the last numpy array (of type == double) the wrapping works and use the <int> version :

```
void auto_dispatch(pybind11::array_t<g_num>&, pybind11::array_t<int>&) [with g_num = int]
```
if i switch the two lines of C++ code, i jump to the <long> overload : 

```
void auto_dispatch(pybind11::array_t<g_num>&, pybind11::array_t<int>&) [with g_num = long]
```

Is it a correct behaviour ? I would prefer an exception TypeError

Maybe i do something wrong ?

Best regards, 
Bruno

**Comment by YannickJadoul** [comment]
@maugarsb First of all, yes, the [order of overloads matters](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order). Since `int32` is safely convertible to `int64`, if that's the first overload pybind11 checks, and it matches, it will use that one.

Second of all, there's a few things you can do to tweak which arguments are accepted. By default, `array_t` has the [`py::array::forcecast` flag set](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#arrays) (corresponding to [`NPY_ARRAY_FORCECAST`](https://numpy.org/doc/stable/reference/c-api/array.html#c.NPY_ARRAY_FORCECAST)), so will do unsafe conversions. You can just change that into `py::array_t<long, 0>` to not set any flags. If you then want to perfectly match the type, also use `py::arg::noconvert()` (this will stop 32-bits integers to be converted to 64, as well).

On a separate, minor note: `long` isn't guaranteed to be 64-bit in C++, as far as I know; I thought it can just be a 32-bit integer, as well? If you want to know the width, use `int32_t` etc.

**Comment by maugarsb** [comment]
Thx for this quick reply. 

My exemple  works well if i do : 

```cpp
PYBIND11_MODULE(dispatch, m) {
  m.doc() = "pybind11 dispatch plugin"; // optional module docstring
  m.def("auto_dispatch", &auto_dispatch<int> , py::arg("face_vtx").noconvert(), py::arg("face_vtx_idx").noconvert());
  m.def("auto_dispatch", &auto_dispatch<long>, py::arg("face_vtx").noconvert(), py::arg("face_vtx_idx").noconvert());
}
```
Regards
