### ISSUE TITLE
[QUESTION] Must a custom exception be static?

### ISSUE THREAD

**Issue by anordal** [pybind/pybind11#2562]
I have followed the recipe for a [custom exception](https://pybind11.readthedocs.io/en/latest/advanced/exceptions.html#registering-custom-translators), and it's working fine:

```c++
void registerExceptions(pybind11::module &m)
{
    static py::exception<MyException> pyException(m, "MyException");
    py::register_exception_translator([](std::exception_ptr p) {
        try
        {
            if(p) std::rethrow_exception(p);
        }
        catch(const MyException &myException)
        {
            pyException(myException.what());
        }
    });
}
```

Turns out that a variable with `static` storage duration is a review comment magnet, and I don't know if it _really_ needs to be static, or if I could hide it in the python module object somehow.

Questions:
1. Could the documentation say something about lifetime? It only says it has to be static in order to be passed to the "stateless" lambda. Which of course makes it stateful – is this the real reason?
2. Do I understand it correctly that the py::exception object has to outlive my registerExceptions() function (because it only runs when my module is imported, whereas the lambda it sets up runs later)?
3. Could I hide it in my python object, perhaps as an attribute? I'm happy to call it "__last_error". I don't suppose there is much functional benefit to it, though.

**Comment by YannickJadoul** [comment]
@anordal, so the main point is that a list of `void (*) (std::exception_ptr)` is stored, internally. So in order to have your lambda convert to a function pointer, it needs to not capture anything. (I'm not entirely sure why that is stored, and not a `std::function<void (std::exception_ptr)`; probably because it's more efficient?).

Making the `py::exception` object static allows you access that thing without capturing it in the lambda. I believe that if you find a way to access that without capturing any variable in that lambda, you should be just as fine. Storing it in Python should be fine, but I'm not sure how you're going to get access to it, then?

**Comment by bstaletic** [comment]
Regarding the lifetime, `py::exception` needs to outlive the lambda which, according to @YannickJadoul, is stored somewhere in pybind11 internals. Thus, the `py::exception` object needs to be alive as long as the python interpreter is running.

If you're embedding the interpreter, you can couple the lifetime of `pyException` with the lifetime of `py::scoped_interpreter`. Otherwise, you can put it on the heap and leak. Or read on [module destructors](https://pybind11.readthedocs.io/en/stable/advanced/misc.html?highlight=cleanup#module-destructors).
