### ISSUE TITLE
[QUESTION] Why is GNUInstallDirs not used in CMakeLists.txt?

### ISSUE THREAD

**Issue by asobhy-qnx** [pybind/pybind11#2571]
Regarding the line below:

https://github.com/pybind/pybind11/blob/59323a975ade742a5904fff23dbd3aecf72ad091/CMakeLists.txt#L181-L184

Why can't it be:

`set(PYBIND11_CMAKECONFIG_INSTALL_DIR "${CMAKE_INSTALL_DATAROOTDIR}/cmake/${PROJECT_NAME}" CACHE STRING "install path for pybind11Config.cmake")`

**Comment by henryiii** [comment]
It was left there due to the comment:` # GNUInstallDirs "DATADIR" wrong here; CMake search path wants "share".`

Though I have no idea what that comment is referring to, as that's exactly what `CMAKE_INSTALL_DATAROOTDIR` and `CMAKE_INSTALL_DATADIR ` is defined to... https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by asobhy-qnx** [comment]
I patch it locally to 

set(PYBIND11_CMAKECONFIG_INSTALL_DIR "${CMAKE_INSTALL_DATAROOTDIR}/cmake/${PROJECT_NAME}" CACHE STRING "install path for pybind11Config.cmake")

**Comment by asobhy-qnx** [comment]
Thank you
