### ISSUE TITLE
[FEAT] Enable generation of sphinx documentation from C++ docstrings via Breathe

### ISSUE THREAD

**Issue by axsaucedo** [pybind/pybind11#2635]
Breathe is a useful plugin for Sphinx that enables automatic conversion from Doxygen documentation into Sphinx, which is particularily useful for C++ class reference documentation. It seems that PyBind11 does use Breathe to keep docstrings and documentation up to date for the PyBind11 project. It would be extremely useful to be able to leverage Breathe for automatic documentation of the Python functions created from C++, especially as large number of C++ projects are starting to use the combination of these tools (Doxygen, Sphinx and Breathe) for their documentation.

**Comment by YannickJadoul** [comment]
@axsaucedo, it might be useful indeed, but do you have any suggestion how this would work? pybind11 works with templates, and has absolutely no way of accessing comments in C++.

The only option I can see, is some kind of post-processing that would generate an external wrapper. If anyone is interested in contributing that, that could be discussed, but otherwise, this is very likely out of scope of the pybind11 project.

**Comment by henryiii** [comment]
Isn't this what [pybind/pybind11_mkdoc](https://github.com/pybind/pybind11_mkdoc) does (may be a bit rough around the edges)? And I do this via CMake macros in GooFit, as well, if you'd like to take a look. Not something for pybind11 itself, though.

**Comment by axsaucedo** [comment]
Oh that's great @henryiii , that looks exactly like what I was looking for - will give it a try
