### ISSUE TITLE
[BUG] Cannot specify py::multiple_inheritance tag if base class is specified via object

### ISSUE THREAD

**Issue by rajkosto** [pybind/pybind11#2659]
As per the documentation, `py::class_<DerivedClass,BaseClass>(m,"MyType",py::multiple_inheritance());` works, however, in my case, I have to specify base class not via template argument, and doing 
```
	auto based = py::class_<BaseClass>(m,"BaseType");
	py::class_<DerivedClass>(m,"MyType",based,py::multiple_inheritance());
```
Gives me static assert error `pybind11.h(1221,51): error C2338: Error: multiple inheritance bases must be specified via class_ template options` which is weird since you can specify that tag when you specify base via template argument (and documentation says you MUST, if there is MI, in order to avoid undefined behaviour, even though I have no issues just omitting it), or even if you specify no base at all.

Visual Studio 2019 16.8.1
pybind11 commit c58758d04915197e16c7c0d8efc3b85c63b765f9

**Comment by YannickJadoul** [comment]
@rajkosto, but you don't specify a single base class? So there's also no need to inform pybind11 that the specified base class is part of a multiple inheritance relationship. It's only necessary when there's one base class specified but multiple in the actual C++ hierarchy.

Cfr. the docs:

> When only one base type is specified for a C++ type that actually has multiple bases, pybind11 will assume that it does not participate in multiple inheritance, which can lead to undefined behavior. In such cases, add the tag multiple_inheritance to the class constructor:
> 
> ```
> py::class_<MyType, BaseType2>(m, "MyType", py::multiple_inheritance());
> ```
> 
> The tag is redundant and does not need to be specified when multiple base types are listed.

**Comment by rajkosto** [comment]
I specify it, but not via template argument, instead via py::class_ object after the (, see the 2 different code examples of doing the same thing i listed.

**Comment by YannickJadoul** [comment]
Oh, right, I see. Apologies!
(Still, wasn't that deprecated? I can't find it in the docs, though.)

However, now that I read the error again, it says

> Error: multiple inheritance bases must be specified via class_ template options

So it seems as if you can't specify the bases of a multiply-inheriting C++ class as arguments to `class_`? (https://pybind11.readthedocs.io/en/stable/advanced/classes.html#multiple-inheritance seems to also say so, but not very clearly)

**Comment by rajkosto** [comment]
You cannot specify more than one base using object, and the docs say so. But they don't say anything about specifying one base and then py::multiple_inheritance tag to avoid the "undefined behaviour", while you can and should do exactly that when using template arg to specify the one base

**Comment by YannickJadoul** [comment]
Well, I don't know. The `static_assert` says it's not possible. I haven't yet looked why it wouldn't be possible, but I'd trust the fact that someone did an effort to put a static assert in, checking for this. Mind you, it's not a compilation error, it's an explicit check saying this doesn't work!

Again, I agree the docs aren't entirely clear, but also don't explicitly state it's possible. And this `static_assert` is quite clear.

If you don't believe me, feel free to dive into the code and have a look yourself. I'm sure something in there makes it impossible to combine `py::multiple_inheritance` with base-class arguments? If not and if it's technically possible, if could be nice adding it.

**Comment by YannickJadoul** [comment]
There you go. For template arguments:

https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/include/pybind11/pybind11.h#L1241

which calls

https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/include/pybind11/pybind11.h#L1254-L1259

which calls

https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/include/pybind11/attr.h#L280-L305

For function call arguments:

https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/include/pybind11/pybind11.h#L1244

which calls

https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/include/pybind11/attr.h#L443-L447

So in other words, without the template argument, pybind11 cannot provide a `static_cast` from one class to the other. And if you have multiple inheritance, the address of one of your base class objects might differ from the address of your derived object. So given `class Derived : public Base1, Base2, Base3`, pybind11 has no clue how to cast a `Derived` object to e.g. `Base2`, if you pass the `py::class_<Base2>` object rather than the template argument.

So the object function call argument approach really is less powerful than the template argument one. Also, "Functionality-wise, both approaches are equivalent." is only stated in the docs long before MI is ever mentioned. Again, not saying I don't agree this could be made more clear in the documentation, restating this at the MI section. A PR to make the docs more complete is welcome :-) (PR also welcome if you would somehow know a way to solve this issue, btw, but I don't think it's going to be trivial.)

**Comment by rajkosto** [comment]
Ah, so py::multiple_inheritance only tells it that there might be an offset from base pointer to get the derived ? And if i only use MI for mixins in c++ (which is why im not exposing those base classes to python), I shouldn't worry about missing py::multiple_inheritance ?

**Comment by YannickJadoul** [comment]
> Ah, so py::multiple_inheritance only tells it that there might be an offset from base pointer to get the derived ?

Not entirely sure, but seems so? 

> And if i only use MI for mixins in c++ (which is why im not exposing those base classes to python), I shouldn't worry about not being able to specify py::multiple_inheritance ?

Well, there's still a difference between "it works" and "it's not undefined behavior". But I'm going to call in @bstaletic on that.

**Comment by YannickJadoul** [comment]
At any rate, do as you please, but pybind11's `static_assert` *explicitly* tells you "MI is not supported when passing the base class as argument".
