### ISSUE TITLE
[BUG] SegFault in `error_scope`

### ISSUE THREAD

**Issue by thorstenhater** [pybind/pybind11#2721]
## Issue description

I am encountering SegFaults in `error_scope` after an upgrade to v2.6.1. The reason
is the addition of `error_scope` to `object` in
https://github.com/pybind/pybind11/commit/4d90f1a1998b394e075660fea1dbaf9d24ea0039

The issue appears under these conditions
- We have constructor that needs to release the GIL to avoid deadlocks, as it is called from 
   multiple threads and needs to call Python code.
- The constructor uses a Python function internally that returns a temporary object. This is 
   also required.

The bug then appears due to the call into `PyErr_Fetch` in `error_scope` without holding the GIL.

## Questions
- Is considered this a bug in pybind11 or our project?
- Is there a way to satisfy both requirements (multi-threading and creation/destruction of user-defined classes) without changes to pybind11?
- Would it be feasible to acquire the GIL in `error_scope`?
- Alternatively, can `error_scope` check whether the GIL is held and react accordingly?
  It could do nothing, as there is no sense in manipulating the interpreter state without the GIL.
  Or throw an error.

Thanks, 
  Thorsten

**Comment by bstaletic** [comment]
> We have constructor that needs to release the GIL [...] and needs to call Python code.

That sounds really wrong. If the constructor is reaching into python, it has to hold the GIL.

**Comment by thorstenhater** [comment]
I know that this is a problem, but this particular line of code was architected to
allow multi-threaded simulations to use functionality extendable in python.
In particular, the call goes through from Python through a wrapped C++ to a 
Python class that inherits from a C++ class.

We assumed here that there is a potential deadlock when multiple threads access
the same Python class. Is that correct?

**Comment by YannickJadoul** [comment]
You can't really call or do anything with the Python interpreter without holding the GIL. Period. I understand that's quite annoying, but doing so really isn't supported by the Python C API (nothing pybind11 can do about that, I'm afraid).

>     * Is there a way to satisfy both requirements (multi-threading and creation/destruction of user-defined classes) without changes to pybind11?

Python (well, CPython) very fundamentally does not support multithreading (which is why it has the popular `multiprocessing` module). So all you can do is release the GIL when you have a piece of C code that doesn't require Python, and reacquire the GIL when you temporarily need it. Does that cause deadlocks?

**Comment by thorstenhater** [comment]
We have concluded this is a bug on our side.

Thank you.
