### ISSUE TITLE
[QUESTION] Transfer numpy ownership to C++

### ISSUE THREAD

**Issue by maugarsb** [pybind/pybind11#2740]
Hello,

Thx for this useful library. I start wrapping a C++ code to expose multiple algorithm in python.

I try to transfer ownership from python to C++ for many reason (data life of the numpy array )

``` cpp 
template <typename T>
struct mdarray {
  typedef T           value_type;
  typedef T*          pointer;
  typedef std::size_t size_type;

public:
  mdarray() = default;

  mdarray(const size_type& size)
   : _data(new T[size]),
     _size(size) {
  }

  mdarray(pointer data, const size_type& size)
   : _data(data),
     _size(size),
     _owner(false) {
    std::cout << "Emplace view mdarray " << this << "\n";
  }

  mdarray(py::array_t<T, py::array::f_style> np_array)
   : _data(np_array.mutable_data()),
     _size(np_array.size()),
     _owner(true)
  {
    std::cout << "Emplace view mdarray " << this << "\n";
    std::cout << "_size " << _size << "\n";
    std::cout << "_data " << _data << "\n";
    np_array.set_flags();
  }
```

The py::array_t<T, py::array::f_style>  is really usefull to initialize my structure from numpy.

In order to change the ownership i add a class method for array_t and the inline method : 

``` cpp
inline setflags(void* ptr, int flag) {
    array_proxy(ptr)->flags &= ~detail::npy_api::NPY_ARRAY_OWNDATA_;
}

 /// If set, the array owns the data (will be freed when the array is deleted)
 int set_flags() {
     return detail::setflags(m_ptr, detail::npy_api::NPY_ARRAY_OWNDATA_);
 }

```

With this fix, the ownership is quitly transfer from python to C++, my test work fine.

Can you implement such function to have control of flags on py::array_t ?

Maybe i miss something, 

Thx !

**Comment by YannickJadoul** [comment]
> In order to change the ownership i add a class method for array_t and the inline method :

First of all, that's not a great idea, extending the API of a library you're using. That'll make things very confusing if you report bugs, later.

> Can you implement such function to have control of flags on py::array_t ?

No, that's not a good idea, as far as I'm concerned, if I understand what you're asking. If NumPy allocates this memory, you cannot really just steal it. First of all, because this memory might be shared with other NumPy arrays. But most importantly, you have no idea how NumPy allocated this memory (`new`, `malloc`, or maybe something exotic), so you don't know how to deallocate this memory.

All in all, as far as I know, NumPy isn't prepared to "release" its allocated memory or doesn't really provide such functionality, so it doesn't seem like a good plan to hack around this. Feel free to prove me wrong with some NumPy docs, if they show that this is supported, though!

**Comment by EricCousineau-TRI** [comment]
100% agree w/ Yannick's points above.

In addition, you should ask yourself - do you *really* need to save that memory? Have you done profiling to ensure you've are now *only* limited by copying memory? (if so, maybe there are better algorithms too?)

If you do, consider exposing a view to NumPy (which is possible for mutable and immutable views), rather than trying to steal memory that NumPy allocated. Some NumPy functions have options to output to a given array.
Just know that you may be in for additional pain ;)

**Comment by YannickJadoul** [comment]
Thanks, @EricCousineau-TRI! Agreed!
Another option is keeping the NumPy object alive and just keeping a non-owning reference to its memory.

@maugarsb, I'll close this issue, but feel free to reopen if we missed something.
