### ISSUE TITLE
[QUESTION] Question about Message "Symbol not found: __Z11rgba_to_rgbRKNSt3__16vectorIhNS_9allocatorIhEEEERKiS7_RS3_"

### ISSUE THREAD

**Issue by dc3505** [pybind/pybind11#2752]
Hi there,

I'm not sure what's going on for this message: Symbol not found: __Z11rgba_to_rgbRKNSt3__16vectorIhNS_9allocatorIhEEEERKiS7_RS3_. I'm new to this, after reading the doc, it seems it says STL types have been auto converted? So, I guess I should be able to directly use allocate vector and manipulate them and return them without extra work? But then, why it says the allocator is not found?

Thanks in advance!

**Comment by YannickJadoul** [comment]
`_Z11rgba_to_rgbRKNSt3__16vectorIhNS_9allocatorIhEEEERKiS7_RS3` (use `, please), can't be demangled. Please just copy-paste the correct symbol.

Also, this is a linker error. You failed to link the object file containing some function (I'm guessing `rgba_to_rgb`, but I don't know, because it's an invalid symbol) to your extension.

Also also, please follow the instructions in the issue and add some minimal example, or at the very least the full error.

At any rate, this is (as far as I can tell from this minimal information), not a pybind11 error.

**Comment by YannickJadoul** [comment]
The symbol in the title works: `__Z11rgba_to_rgbRKNSt3__16vectorIhNS_9allocatorIhEEEERKiS7_RS3_`
So you should have surrounded your code with ... (surprise) markdown to indicate it's code.

That demangles to `

_rgba_to_rgb(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, int const&, int const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&)`. That doesn't change my analysis, though. You did something wrong to link and you are getting a very ordinary link error (as with normal C++). Not a pybind11, as far as I can tell.

**Comment by dc3505** [comment]
Thanks for answering this silly question...may I ask how did you get convert this message to something readable?

**Comment by bstaletic** [comment]
Your toolchain comes with `c++filt`. Try running the mangled name through that.

**Comment by YannickJadoul** [comment]
Yes. Or http://demangler.com/, if you prefer that.
