### ISSUE TITLE
[QUESTION] Chrono bindings and negative datetime.timedelta

### ISSUE THREAD

**Issue by ADKaster** [pybind/pybind11#2861]
Hi,

I was looking at the type caster for datetime.timedelta --> steady_clock::duration and thought that the choice of uint_fast32_t as `rep` for `days` was a bit odd.

https://github.com/pybind/pybind11/blob/417067eeb8d93e8ed49f3ff580712ae2b9a85259/include/pybind11/chrono.h#L38

In the python3 docs (https://docs.python.org/3/library/datetime.html#datetime.timedelta.min), it says that timedelta.min is -999999999 days and timedelta.max is 999999999 days. Neither of these limits are representible in a 32bit unsigned integer.

Looking at the source of CPython they store days in an `int` (which also seems odd).

https://github.com/python/cpython/blob/cc54001c2eb3b14320c1667b22602d69c90d5865/Include/datetime.h#L38

This looks to me like if I pass `timedelta(days=-1)` or `timedelta(seconds=-1)` (which then turns into  `timedelta(days=-1, seconds=86399`) to a C++ function that expects chrono::nanoseconds, pybind11 will do some signed --> unsigned --> signed math under the hood? Is this UB or fine?

So questions:

- Is it fine to use uint_fast32_t here? Should int64_t be used instead?
- Am I misunderstanding the use of std::ratio? i.e. does that struct have an impact on the correctness of the choice for `days`?
- Should there be more tests with negative time deltas? (probably yes :) ).

**Comment by bstaletic** [comment]
Sooo... `days(PyDateTime_GetDats(o))` will preserve the bit pattern. No UB there. Note that on amd64 `uint_fast32_t` is the same as `uint64_t`. This means that the signed "things" will be converted to unsigned. Thus no UB when doing `days + seconds + microseconds`. What can happen is a wraparound, as the result of `days + seconds + microseconds` is in `microseconds`. Finally we have an explicit cast to user's `duration<rep, period>` where we have a ratio conversion to `period` and then an assignment to `rep`. The ratio conversion may be lossy, but not UB. The assingment to the internal `rep` is another modulo operation - if it fits, cool, if it doesn't cut off some bits.

So there's no UB here at all, thankfully. At least for amd64 architectures. In case of x86 `uint_fast32_t` is `uint32_t` in which case all arithmetic is done in `int64_t` and arithmetic overflow could result in UB.


Now for your specific questions:

> Is it fine to use uint_fast32_t here? Should int64_t be used instead? Should int64_t be used instead?

Not sure... Every standard library is using `int64_t` for `chrono::seconds` and `chrono::microseconds`. However signed overflow due to `days + seconds + microseconds` is UB. Right now there's definitely no UB for 64bit architectures, but a wraparound can be just as bad as UB.

> Am I misunderstanding the use of std::ratio? i.e. does that struct have an impact on the correctness of the choice for days?

I'm not sure what you're asking, but maybe something of the above answers the question?

> Should there be more tests with negative time deltas? (probably yes :) ).

More tests is always a good thing. Are you volunteering?

**Comment by ADKaster** [comment]
Thanks for the quick reply!

For 64-bit architectures it makes sense that this should be fine, as most (all?) compilers will use a 64-bit integer for uint_fast32_t. I'm a bit concerned about 32-bit however. Some projects I work on are using pybind11 for some code running on 32-bit and 64-bit ARM.

Does the CI for pybind11 test on any 32-bit platforms?

My ratio question was answered yeah. 

I think I'm volunteering to write some negative timedelta tests, I can take a look later this week on how to get that setup on my home computer.

**Comment by bstaletic** [comment]
Hmm, let me thing. If `GetDays()` returns `-1`, then `days()` will hold `UINT32_MAX`. Then, when doing `days + seconds`, `days` need to be converted into `int64_t` and preserve the value, which means sign-extending `UINT32_MAX` to `-1LL`. From what I can tell, it should all work even on 32bit architectures. The only difference being what happens when you go past `INT64_MAX` vs `UINT64_MAX`.

I'm not sure how many 32 bit runs does the CI have, but there's at least one 32bit Windows there.

**Comment by knzivid** [comment]
Coincidentally I hit the same problem this morning! My unit test involves converting `-6313214 days` in python to std::chrono::microseconds in C++. C++ supports 106M days with microseconds type `std::chrono::duration_cast<std::chrono::days>(std::chrono::microseconds::min()).count()`. I should be able to convert `-6313214 days` losslessly from python to C++ because this is a valid timedelta in both python and C++.

This is on 64 bit MSVC 14.16 where `uint_fast32_t => unsigned int` is [32 bits](https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-160). 

```cpp
typedef unsigned int       uint_fast16_t;
typedef unsigned int       uint_fast32_t;
typedef unsigned long long uint_fast64_t;
```

The change from signed rep type to unsigned type happened in a3603e6df0bc72b652ca76eeec8d0fdccebf15da

```diff
-    typedef std::chrono::duration<Rep, Period> type;
-    typedef std::chrono::duration<std::chrono::hours::rep, std::ratio<86400>> days;
+    typedef typename type::rep rep;
+    typedef typename type::period period;
+
+    typedef std::chrono::duration<uint_fast32_t, std::ratio<86400>> days;
```

Both python and C++11 have negative time deltas, so I don't know why this commit changed it from a signed representation to an unsigned one.

**Comment by bstaletic** [comment]
@knzivid https://godbolt.org/z/nq3Enz

As you can see, the arithmetic is lossless even now with `uint_fast32_t`. What's more, you can see that changing the type to `int64_t` doesn't change the final value. So the real question is which type are you expecting to get on the other end? Is it `std::chrono::days`?

> Both python and C++11 have negative time deltas, so I don't know why this commit changed it from a signed representation to an unsigned one.

https://github.com/pybind/pybind11/pull/356#discussion_r80364254

But I assure you that on 32 bit systems the arithmetic is done in `int64_t` anyway, because `uint32_t` is smaller.

**Comment by knzivid** [comment]
I will try making a minimal reproducer for my test case.

Roughly it looks like

```
# First convert from python to C++
t = T(timedelta(days=-6313214))

// The C++ constructor looks like
T(std::chrono::microseconds t);

# Finally I convert it back to python
print(t.value) # value here is a property that returns a std::chrono::microseconds and is automatically cast by pybind11
```

**Comment by knzivid** [comment]
`main.cpp`

```cpp
#include "pybind11/chrono.h"
#include "pybind11/pybind11.h"

class MicroSeconds {
public:
    explicit MicroSeconds(std::chrono::microseconds microseconds) : mData(microseconds) {}
    auto value() const { return mData; }
    void setValue(std::chrono::microseconds data) { mData = data; }
    std::string toString() { return std::to_string(std::chrono::duration_cast<std::chrono::microseconds>(mData).count()) + " us"; }

    static constexpr auto min() { return decltype(mData)::min(); }
    static constexpr auto max() { return decltype(mData)::max(); }

private:
    std::chrono::microseconds mData;
};

PYBIND11_MODULE(cppusec, module) {
    auto clazz = pybind11::class_<MicroSeconds>(module, "MicroSeconds");
    clazz.def(pybind11::init<std::chrono::microseconds>());
    clazz.def_property("value", &MicroSeconds::value, &MicroSeconds::setValue);
    clazz.def_property_readonly_static("min", [](const pybind11::object & /*object*/) { return MicroSeconds::min(); });
    clazz.def_property_readonly_static("max", [](const pybind11::object & /*object*/) { return MicroSeconds::max(); });
    clazz.def("__repr__", &MicroSeconds::toString);
}
```

`test.py`

```python
from cppusec import MicroSeconds
from datetime import timedelta

lower: timedelta = MicroSeconds.min
upper: timedelta = MicroSeconds.max

cases = [MicroSeconds.min, MicroSeconds.max]

for case in cases:
    print(f"# Testing {case}")
    print("Value in python\t", case.total_seconds() * 10 ** 6)
    print("Python -> C++\t", MicroSeconds(case))
    print("C++ -> Python\t", MicroSeconds(case).value.total_seconds() * 10 ** 6)
    print()
```

`CMakeLists.txt`
```cmake
add_subdirectory(deps/pybind11-2.6.2)
pybind11_add_module(cppusec MODULE main.cpp)
```

---

**Output** with `days = std::chrono::duration<int64_t, std::ratio<86400>>`

```
# Testing -106751992 days, 19:59:05.224192
Value in python  -9.223372036854776e+18
Python -> C++    -9223372036854775808 us
C++ -> Python    -9.223372036854776e+18

# Testing 106751991 days, 4:00:54.775807
Value in python  9.223372036854776e+18
Python -> C++    9223372036854775807 us
C++ -> Python    9.223372036854776e+18
```

Default **Output** with `days = std::chrono::duration<uint_fast32_t, std::ratio<86400>>`

```
# Testing -106751992 days, 19:59:05.224192
Value in python  -9.223372036854776e+18
Python -> C++    -7073079136645808128 us
C++ -> Python    -7.073079136645808e+18

# Testing 106751991 days, 4:00:54.775807
Value in python  9.223372036854776e+18
Python -> C++    9223372036854775807 us
C++ -> Python    9.223372036854776e+18
```

---

I reduced `pybind11/chrono.h` to this snippet

```cpp
#include <chrono>
#include <iostream>

int main() {
    using namespace std::chrono;
    using type = microseconds;
    using rep = typename type::rep;
    using period = typename type::period;

    {
        using days = std::chrono::duration<uint_fast32_t, std::ratio<86400>>;
        auto value = type(duration_cast<std::chrono::duration<rep, period>>(
                days(-106751992) + seconds(71945) + microseconds(224192)));

        std::cout << "With uint_fast32_t" << std::endl;
        std::cout << "c++ min: " << std::chrono::microseconds::min().count() << std::endl;
        std::cout << "chrono.h output: " << value.count() << std::endl;
    }

    {
        using days = std::chrono::duration<uint64_t, std::ratio<86400>>;
        auto value = type(duration_cast<std::chrono::duration<rep, period>>(
                days(-106751992) + seconds(71945) + microseconds(224192)));

        std::cout << std::endl << "With uint64_t" << std::endl;
        std::cout << "c++ min: " << std::chrono::microseconds::min().count() << std::endl;
        std::cout << "chrono.h output: " << value.count() << std::endl;
    }
}
```

prints 

```
With uint_fast32_t
c++ min: -9223372036854775808
chrono.h output: -7073079136645808128

With uint64_t
c++ min: -9223372036854775808
chrono.h output: -9223372036854775808
```

**Comment by bstaletic** [comment]
@knzivid can you test with `int32_t` as well? The standard mandates at least 25 bit wide signed type.

**Comment by knzivid** [comment]
Reduced `pybind11/chrono.h`

```
With uint_fast32_t
c++ min: -9223372036854775808
chrono.h output: -7073079136645808128

With int32_t
c++ min: -9223372036854775808
chrono.h output: -9223372036854775808
```

test.py with modified `pybind11/chrono.h`

```
# Testing -106751992 days, 19:59:05.224192
Value in python  -9.223372036854776e+18
Python -> C++    -9223372036854775808 us
C++ -> Python    -9.223372036854776e+18

# Testing 106751991 days, 4:00:54.775807
Value in python  9.223372036854776e+18
Python -> C++    9223372036854775807 us
C++ -> Python    9.223372036854776e+18
```

**Comment by themarpe** [comment]
@bstaletic Thanks for the PR. 
Spent the evening debugging this on `Mac mini (2018) - Intel Core i3, 8 GB, macOS Big Sur v11.2.1` (vs amd64 Ubuntu20.04 development environment)
Applied your current changes and it resolves the issue.

My minimal case:
```
m.def("test", [](std::chrono::microseconds us){
    printf("us: %lld\n", us.count());
}, py::arg("us") = std::chrono::microseconds(-1));
```
And on python side
```
m.test()
```

Before: `us: 2150292900208967679` after: `us: -1`.
