### ISSUE TITLE
[QUESTION] module::add_object & object deletion

### ISSUE THREAD

**Issue by jeanga** [pybind/pybind11#2887]
Hi!

I want to limit the use of global variables in my pybind11 module.

To achieve this, I have explored the add_object() method of py::module_.

My goal would be to add values there as they are needed or remove them when no longer required.

From my c++ code, I access those members via:
```cpp
// get an existing module or throws `value_error`.
py::module_ MyModule::GetModule(const char* name)
{
    py::str module_(name);
    PyObject* obj = PyImport_GetModule(module_.ptr());
    if (!obj)
        throw py::value_error();
    return py::reinterpret_steal<py::module_>(obj);
}

/// get an existing module or throws `value_error`.
py::object MyModule::GetObject(const char* name, const char* module_)
{
    py::module_ m = GetModule(module_);
    if (!m)
        throw py::value_error();

    return (py::object)m.attr(name);
}
```
Which "appear" to work as expected.

Howver, the documentation says:
https://pybind11.readthedocs.io/en/stable/reference.html?highlight=add_object#_CPPv4N7module_10add_objectEPKc6handleb
```
overwrite should almost always be false: attempting to overwrite objects that pybind11 has established will, in most cases, break things.
```
Which I don't really understand and makes me wonder if those "properties" associated with modules can be born, live and die.
(and if so, how?)

I also want to take this opotunity to thank the pybind11 team for the incredible work they have done with this library I rely on daily!

**Comment by YannickJadoul** [comment]
@jeanga, as far as I know the "dangerous" part is when e.g. do this:

```c++
py::class<Foo>(m, "Foo");
m.attr("Foo") = 42;
```

The reason this is dangerous is because pybind11 keeps internal references to that `py::class_` object and next time you try to cast a `Foo` object to Python, pybind11 will still try to access that (maybe now deleted) `Foo` class Python object, which is not a good plan if you don't intend on segfaulting.

Things might have gotten slightly better, over the last half year, as there's been one or a couple of PRs cleaning up. But AFAIK `py::class_` objects still don't really expect to be cleaned up.

**Comment by jeanga** [comment]
Ok, I "think" I understand the issue better now. 
I was under the impression that the "bond" between the module instance and the attribute was at python runtime only.
Based on your statement, it seems the "bond" is also created between the c++ module object file and the object.
I'll close this issue for now...
Thank you for taking the time to answer my question!
