### ISSUE TITLE
custom object deleter is not called

### ISSUE THREAD

**Issue by foxtog** [pybind/pybind11#327]
I have a class 
```
class C {
public:
   C() {}
};
```
which I register the following way
```
class_<C>(m, "C")
    .def(init<>())
    .def("__del__",
           +[](const C&) -> void { 
               std::cerr << "deleting C" << std::endl;
           }
    );
```
And in Python
```
import ext
c = ext.C()
del c
```
What I expect is `__del__` being called i.e. get `deleting` printed but it doesn't work out.
Probably, there is a flaw in my setup. But the same setup works as expected with `Boost.Python`.

**Comment by foxtog** [comment]
I've come accross the following line in the code
```
type->ht_type.tp_dealloc = rec->dealloc;
```
Is it the reason for `del` not being called?

**Comment by jagerman** [comment]
No, `tp_dealloc` happens much later; it's not being called because pybind11 doesn't define a `tp_del` function with something that looks for `__del__` and calls it (for extension classes Python calls the object's `tp_del` function instead of looking for a `__del__`).

Defining `tp_del`, however, changes Python's garbage collection behaviour, so it would probably need some detailed testing to make sure instances still get cleaned up as expected.

**Comment by foxtog** [comment]
Please, correct me if I'm wrong: as I can see in `boost.python`, `tp_del` is not defined for created objects there as well. Nevertheless, the same test works well i.e. overloaded `__del__` is called.

**Comment by wjakob** [comment]
What's wrong with just using the destructor of ``C``?

**Comment by wjakob** [comment]
I'll close this for now. ``__del__`` is a fairly problematic concept even in Python since it messes with the garbage collector. In C++, we have much cleaner abstraction for this with is the destructor (which is supported by pybind11).

**Comment by TheDiscoMole** [comment]
is there any way to do a custom destructor at all? Out of necessity my classes have a member function called __del__ to interface with pybind that clears internally allocated memory. Any way to correctly override __del__ with pybind11?
