### ISSUE TITLE
[BUG]: await statement blocks forever and doesn't return the result of asyncio.Future on done 

### ISSUE THREAD

**Issue by MarshalX** [pybind/pybind11#3597]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

`await` statement doesn't work properly (blocks for forever) with `asyncio.Future` that was returned to Python without result and the result was set in another thread after returning the future.

### Reproducible example code

Repository with project that can reproduce the issue: https://github.com/MarshalX/pybind11-async-issue

main.py
```python3
import asyncio

import async_issue


# it's a trick
async def wrap(future):
    on_done_event = asyncio.Event()

    def _done_callback(_):
        on_done_event.set()

    future.add_done_callback(_done_callback)
    await asyncio.wait_for(on_done_event.wait(), timeout=10)

    return future.result()


async def main():
    r = await async_issue.test()
    # works fine
    print('Awaited result of future without thread', r)

    r = await wrap(async_issue.thread_test())
    # works fine (with big delay)
    print('Wrapped future with add_done_callback trick', r)
    r = await async_issue.thread_test()
    # blocked forever. This print doesn't appear
    print('Awaited result of future without wrapping', r)


if __name__ == '__main__':
    loop = asyncio.get_event_loop().run_until_complete(main())

```

module.cpp
```cpp
#include <chrono>
#include <thread>

#include <pybind11/pybind11.h>

namespace py = pybind11;

static py::object test() {
  py::object loop = py::module_::import("asyncio.events").attr("get_event_loop")();
  py::object f = loop.attr("create_future")();

  f.attr("set_result")(5);

  return py::object{f};
}

static void thread_task(py::object future)
{
  int delay_in_sec = 1;
  std::this_thread::sleep_for(std::chrono::milliseconds(delay_in_sec * 1000));

  py::gil_scoped_acquire acquire;
  future.attr("set_result")(5);
  py::gil_scoped_release release;
}

static py::object thread_test() {
  py::object loop = py::module_::import("asyncio.events").attr("get_event_loop")();
  py::object f = loop.attr("create_future")();

  std::thread thread(thread_task, py::object{f});

  py::gil_scoped_release release;
  thread.detach();

  return py::object{f};
}

PYBIND11_MODULE(async_issue, m) {
  m.def("test", &test);
  m.def("thread_test", &thread_test);
}
```

#### Actual output of main.py
```
Awaited result of future without thread 5
Wrapped future with add_done_callback trick 5
```

#### Expected output of main.py
```
Awaited result of future without thread 5
Wrapped future with add_done_callback trick 5
Awaited result of future without wrapping 5
```

**Comment by eirrgang** [comment]
This looks like a misuse of `asyncio` rather than anything to do with pybind.

In general, asyncio is explicitly not thread-safe. Even if you can get it to work, calling set_result on an asyncio Future is not a supported use case. You should either use a `concurrent.futures.Future` or a `loop.call_soon_threadsafe` to wrap the call. Even if you can get this to work, I don't think it is the right approach. See also https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

If you look at the way asyncio.Future is implemented, you can see that there is no way for it to handle this case on its own. The Task and Future expect everything to be happening in terms of the normal progress of the event loop. There aren't extra places to yield if you await directly on that Future. If you don't end up using the Python concurrency stuff, and want to just use `loop.call_soon_threadsafe`, `asyncio.run_coroutine_threadsafe`, etc. you would need to make sure there is at least one other participant in the event loop before awaiting, I think, or the event loop will have no other awaitables to yield to, and you'll probably never get a chance to acquire the GIL.

Also note that the "scoped" versions of the GIL commands use RAII semantics. You do not need to explicitly release a scoped acquisition because it is released when the object is destroyed at the end of the block.

**Comment by MarshalX** [comment]
@eirrgang thanks for the answer! Oh, exactly, not thread-safe... In that case, all attempts to work with asyncio are dirty ways...

Thanks for info about RAII semantics!

Can you tell me please how, in this case, to implement the return of a value to python from another thread? Was it worth just calling the Python callback function when job will done? How to call it safely (I am worrying about GIL)? Is there any general approach to writing something like this? The way that I can wrap, for example, to my custom promise impl to use with async.

**Comment by eirrgang** [comment]
> In that case, all attempts to work with asyncio are dirty ways

I'm not sure that's true. If you want to handle asynchronous results in terms of an event loop, asyncio is a good way to go. If you want to use Futures semantics for thread-based tasks, concurrent.futures is a good way to go. If you want to do both, [wrap_future](https://docs.python.org/3/library/asyncio-future.html#asyncio.wrap_future) provides the bridge.

> Can you tell me please how, in this case, to implement the return of a value to python from another thread?

Presumably you mean "... without blocking"? If blocking is okay, just block at the C++ level and wait for the threads to finish.

In order to make sure that multiple OS-level threads get access to the GIL at reasonable times, your best bet is to use the Python facilities for managing threads. Launch the threads with either [asyncio.run_coroutine_threadsafe()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) or just with the concurrent.futures.ThreadPoolExecutor.

Alternatively, just confine all of your interaction with the Python interpreter to a single thread and manage the multithreading entirely on the C++ side. As long as the GIL is released in the scope where you are managing the threads, Python-driven threads could execute in parallel.

Or you could still get single-threaded concurrency in Python by yielding while waiting for your threads to finish. I don't think pybind has support for https://docs.python.org/3/c-api/typeobj.html#async-structs and I haven't seen any examples of people writing C/C++ based awaitables, but in C, C++, or Python, you could implement the `__await__` dunder and `yield None` on iterations where the thread results are not available yet.
