### ISSUE TITLE
CMake adds postfix to debug builds of the test shared library

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#365]
This is a bit of a PITA for development:

```
- Found PythonInterp: /Users/ivansmirnov/.pyenv/shims/python3.4 (found version "3.4.4") 
-- Found PythonLibs: /Users/ivansmirnov/.pyenv/versions/3.4.4-debug/lib/libpython3.4dm.dylib
...
-- Setting tests build type to MinSizeRel as none was specified
...
Linking CXX shared module ../../tests/pybind11_tests_d.so
```

-- then you have to rename the `.so` file manually every time after rebuild because of the stupid `_d` postfix, or symlink it or something. Does anyone know how to remove it in cmakelists?

I've tried setting `CMAKE_DEBUG_POSTFIX` and a few other things but that doesn't seem to do it (OS X, Python 3.4.4-debug, cmake 3.5.2).

**Comment by wjakob** [comment]
That is interesting -- when working with debug builds of Python in the past, I've found that it explicitly needs a "d" or "_d" suffix (don't remember) or imports will fail. Are you saying that this is not true anymore?

**Comment by dean0x7d** [comment]
The extra `_d` is set [here](https://github.com/pybind/pybind11/blob/36919ea6955a790c2c61a2cdc44f7796027b5532/tools/FindPythonLibsNew.cmake#L139), but the comment right above does state `# TODO: All the nuances of CPython debug builds have not been dealt with/tested`. The `FindPythonLibsNew.cmake` file dates back to before Python started using ABI tags for extension modules, which should have solved this issue. The `PYTHON_MODULE_EXTENSION` in CMake is determined as the result of running:
```python
from distutils import sysconfig
sysconfig.get_config_var('SO')
```
I just checked on Linux and the release and debug builds of Python 3.5 return `.cpython-35m.so` and `.cpython-35dm.so` respectively. Python 2.7 returns `.so` and `_d.so`. This also works as expected on Windows. So it would seem that manually adding `_d` is not needed since the string returned by `sysconfig.get_config_var('SO')` already has it.

@aldanor Can you check that `sysconfig.get_config_var('SO')` returns the correct extension for the debug build on OS X? If so, then the simplest thing is to just delete the [unnecessary lines from FindPythonLibsNew.cmake](https://github.com/pybind/pybind11/blob/36919ea6955a790c2c61a2cdc44f7796027b5532/tools/FindPythonLibsNew.cmake#L137-L140).

**Comment by aldanor** [comment]
OSX:

- 2.7.12-dev: `.so`
- 2.7.10: `so`
-3.4.4-debug: `.so`
- 3.5.1: `.cpython-35m-darwin.so`
- 3.6-dev: `.cpython-36m-darwin.so`
