### ISSUE TITLE
pybind::buffer_info view double deletion

### ISSUE THREAD

**Issue by nevion** [pybind/pybind11#377]
Perhaps I am not using the desired use strategy of buffer_info, but I'll assume I am for now.

I use buffer_info's to extract out the information from pybind::array types (for numpy).

I wrote some routines to extract (return) buffer_info's from a py object covering a few different cases.

I started getting some very odd crashes that took me some time to figure out due to their double free nature and scoping of automatic storage variables/destructors.

As it turns out the problem boils down to this:

`py::buffer_info a = ndarray.acquire(); //OK`
````
py::buffer_info a {};
a = ndarray.acquire(); //NOT ok
```

My solution was to add move constructors and move assignment operators to py::buffer_info and write it as so:
````
py::buffer_info a {};
a = std::move(ndarray.acquire()); //works, but does this minimize user error/what library users would normally enter?
```

Perhaps it is better to use std::unique_ptr or std::shared_ptr, however I can think of issues with all of these approaches.  unique_ptr will mean we can't simply copy the buffer_info... and well, it's just info, right? At least at face value.  With shared_ptr, we get into the muddled waters of doubly referenced counted (on the python side, and on the C++ side),  and the increased possibility that the user leaves dangling python objects (views) around.  Perhaps we should also subclass buffer_info's who come from memoryview's so they don't pay the penalty of unnecessary shared_ptr's.

All things considered, I believe shared_ptr may be the most behaved and least error-prone (for users) approach.

If you want the move ctor/assignment operator, I'll be happy to submit a PR.  I added some other things to perform as expected more often as well.

**Comment by jagerman** [comment]
This looks like a bug to me: `buffer_info` is currently copyable, but shouldn't be.  I've submitted PR #378 to address that: it makes buffer_info movable, but not copyable (right now the compiler allows copying but not moving, but the copying results in a double-free, as you discovered).

> unique_ptr will mean we can't simply copy the buffer_info... and well, it's just info, right?

Copying a `buffer_info` won't actually copy everything: the ptr will still point to the same place, but the other fields will get copied.  I'm not sure that being able to copy makes sense given that it really *won't* be copying the data, but is rather copying a reference to it.

> I wrote some routines to extract (return) buffer_info's from a py object covering a few different cases.

What are those routines doing and returning?  In particular, in the code below, what type is `ndarray`, and what does `ndarray.acquire()` return?

> ```C++
> py::buffer_info a = ndarray.acquire(); //OK
>
> py::buffer_info a {};
> a = ndarray.acquire(); //NOT ok
> 
> py::buffer_info a {};
> a = std::move(ndarray.acquire()); //Works
> ```

I'm guessing that `acquire()` is returning a `buffer_info&`—but then the third one is stealing that reference, leaving the `buffer_info` that `ndarray` references in some indeterminate state.  If the objective here is to have `a` and `ndarray.acquire()` share data, this is almost certainly wrong—you can't depend on anything in `ndarray`'s `buffer_info` having any particular value after 3.

If my guess is correct, is there a reason to not simply take a reference to the `buffer_info` rather than trying to copy it, as in:

`py::buffer_info &a = ndarray.acquire();`

**Comment by nevion** [comment]
buffer_info seems to be pulling in responsibility of memory view object ownership, which I don't think covers all cases - sometimes we just want to use it from a memoryview we got another way, but don't want to destroy the memory view reference.  buffer_info certainly doesn't, through it's naming, imply this responsibility - that is why I meant when I said "it's just info".

My case came from having to handle both ndarray's and np.void objects.   The latter being an instance of a record in an ndarray.  In order to get a buffer_info on such a scalar, I used the data field of the np.void object.

Re the third line, I added default values for all fields, and the move constructor swapped all the fields.  So the rhs object became the default constructed values.  See patches in #379.

pybind::buffer::request returns by value and pybind::array inherits from buffer.

**Comment by jagerman** [comment]
> My solution was to add move constructors and move assignment operators to py::buffer_info and write it as so:

The PR seems reasonable.  Note that adding the move ctor./assignment op implicitly deletes the default copy ctor./assignment op (which is good; this shouldn't be copyable).  It might be worthwhile making this explicit in the PR by adding:

```C++
buffer_info(const buffer_info &) = delete;
buffer_info &operator=(const buffer_info &) = delete;
```

(although that's already the current implicit behaviour with a move constructor or move assignment operator, it has the advantage of giving a more direct compilation error if you try to copy).

I think I was confused before when you said changing it to this worked:

`a = std::move(ndarray.acquire());`

because I can't see how that will be any different from:

`a = ndarray.acquire();`

assuming `acquire()` is returning by value: it's *already* an rvalue, so the `std::move` shouldn't change anything.  I'm pretty sure it's adding the move constructor and assignment operator that fixes it, not the `std::move`.

**Comment by nevion** [comment]
alright, I'm still hesitant to joint the buffer_info is not copyable club, but there we go.

I'm still green on rvalues/moves so I put them there for extra explicitness. I kind of think its a good reminder too, of what's happening.

**Comment by jagerman** [comment]
> alright, I'm still hesitant to joint the buffer_info is not copyable club

Well, you *could* implement a copy by copying everything except `ownview`, setting `ownview` to false: the original would keep ownership, the copy wouldn't.  This has a major problem though: if I make a copy, then let the original be destroyed, `view` is now pointing to freed memory.  So a copy wouldn't be so much copying as referencing the original.  That doesn't seem ideal.  You could maybe work around this by copying the `ownview` value, then using a `shared_ptr` with a custom deleter that doesn't actually do the deletion if the first object was initialized from an externally-owned pointer—but that's getting messy.

And now that I think about it, the same lifetime problem is in the current version with `ownview = false`: `view` is only valid as long as the actual owner is still alive, but we have no way to know whether that is the case (aside from just being careful).  Perhaps there's a better way around the whole thing, but I'm not really sure what that would be.

---
> I'm still green on rvalues/moves so I put them there for extra explicitness. I kind of think its a good reminder too, of what's happening.

A bit off-topic, but a simple rule of thumb: any value that is "in transit," i.e. that won't exist after the current expression, is automatically an rvalue.  The danger with throwing an `std::move` around something is that the whole point of `std::move` is to convert lvalue references into rvalue references.  Sometimes you explicitly want to do that, usually when you don't intend to use a local variable again, and that's exactly what `std::move` is about: "I know this value is an lvalue, but I'm not going to use it again, so do what you want with it."  You won't break anything putting it around something that is already an rvalue, but you may well if you unintentionally put it around an lvalue.

**Comment by nevion** [comment]
This technique shared_ptr with custom deleter and ownview (for ownership) what cv::Mat and various image wrapping classes do when taking raw pointers that to map least common denominator external data into their objects.

**Comment by aldanor** [comment]
Should this be closed now that #379 is merged in?

**Comment by jagerman** [comment]
Probably, though I think @wjakob and/or @nevion should comment on whether the `shared_ptr` approach and copying support are worthwhile additions.

**Comment by wjakob** [comment]
I feel like not having ``shared_ptr`` semantics for the underlying Python buffer pointer has caused a whole bunch of issues for users of this project. I think I'm open to the idea if the change is reasonable. AFAIK, this ``shared_ptr`` will only live on the C++ side and will be managed by ``buffer_info``, so there are none of the usual issues with potential duplicate (but mutually unaware) shared pointers.

**Comment by nevion** [comment]
Honestly I think shared_ptr is the better approach though it opens another awkwardness - but it is the lesser of 2 evils.

**Comment by wjakob** [comment]
I'll close this for now since the ``unique_ptr`` patch was merged. Any patches which change the current implementation over to ``shared_ptr`` should be handled in a separate PR.
