### ISSUE TITLE
Extra parameter for PYBIND11_OVERLOAD_INT to specify arguments `call value policy`

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#412]
Dear Pybind11 team,

Would it be possible to add extra argument to PYBIND11_OVERLOAD_INT macro for specifying `pybind11::return_value_policy` for function arguments? I have functions in my project that require special custom return_value_policy so i have to expand PYBIND11_OVERLOAD_INT 'by hands'. But PYBIND11_OVERLOAD_INT code became quite volatile so this approach became error prone and require frequent refactoring due to Pybind11 updates.

Thanks,

**Comment by wjakob** [comment]
Also related to this: currently, specifying policies can only be done at a very coarse level whereas more fine-grained policies may be needed in certain cases (e.g. per argument). There is no way that such specific requirements can be satisfied with the current macro-based approach (and there is already a sort of macro explosion happening at the moment)

**Comment by jagerman** [comment]
I thought about methods of dealing with this without needing extra macros when I was in there for PR #400, and really couldn't come up with any obviously good way to solve it.  The main issue is that we need to `return` from the macro, and propagate that to actually return from the caller.  A couple things that I considered that might work:

- Have an `overload` function that takes arguments as the usual `template... Extra` types that returns a `std::pair<bool, ret_type>`, where the "return now" (i.e. overload found) is captured in the bool.  That gets a little messier when `ret_type` is a reference type, because you need to use an `std::pair<bool, std::reference_wrapper<ret_type>>`, *and* the caller has to worry about unpacking the pair, but it might still work.
- Alternatively, and this is probably the better option, modify the base macro to take the whole overload call, rather than just the call arguments, as a macro parameter instead of the arguments; the default use (by the existing macros) would become: `PYBIND11_OVERLOAD_BASE(ret_type, cname, name, overload(__VA_ARGS__))`, but then people with other needs could invoke, for example, `PYBIND11_OVERLOAD_BASE(ret_type, cname, name, overload<pybind11::return_value_policy>(arg1, arg2, arg3))`.  (I haven't tested that, but I'm pretty sure the `,`s will be okay there since they are nested inside brackets).

**Comment by wjakob** [comment]
A related confusion is that return value policies for overrides go the other way, so it would make more sense to call them argument value policies (or just "value policies" for both of them)?

**Comment by wjakob** [comment]
This ticket has been lingering here, and it's not really clear what to do. (IMHO the OP's requested flexibility is not simply practical to implement with the macro-based approach).

I'm leaning towards closing as "WONTFIX" (not that this option actually exists on github ;)). This means that we keep the current set of macros. Those who want to venture further will need to expand the macros themselves (to PYBIND11_OVERLOAD_INT, which is internal API and potentially unstable or even beyond, which may actually make things more stable again).

**Comment by lyskov** [comment]
That make sense - thank you for checking on this @wjakob !

**Comment by wjakob** [comment]
Sounds good.
