### ISSUE TITLE
Catching exceptions thrown in threads

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#413]
I have a library that forks a couple of worker threads using C++11 threads, and when a worker thread throws an exception, python just crashes, without invoking the exception handler in pybind11, which is obviously not that nice.  Is there any way to invoke the error translator in pybind11, or must I do all the error handling within the thread, and somehow pass that message back to the master thread?

**Comment by dean0x7d** [comment]
Without a code example it can be difficult to work out exactly what's happening in your case. That said, my guess is that you're using raw `std::thread`. In that case, this isn't really a pybind11 issue, since this is a fundamental danger with `std::thread`: an unhandled exception will call `std::terminate`. You are expected to manually do all the exception handling when working with `std::thread` (it's the threading equivalent of a raw pointer). As a solution, you could try switching to `std::future` and `std::async` which do automatically handle the propagation of exceptions (the master thread which invokes `std::future::get()` will be expected to handle the exception).

**Comment by ianhbell** [comment]
This was precisely my fear.  I do use ``std::futures`` and ``std::async`` in my threading implementation, but also ``std::thread`` in other places.

**Comment by wjakob** [comment]
closing as this is not related to pybind11.
