### ISSUE TITLE
[BUG]: Cannot specify author, version, credits and date in pybind11

### ISSUE THREAD

**Issue by henrywoo** [pybind/pybind11#4153]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

This is more like an enhancement. Currently the module built by pybind11 only has attribute `doc` or `__doc__` available. We should do the same for other package attributes like author, version, credits and date.

**Comment by henryiii** [comment]
These are not standard. The last attempt at standardization failed (in 2011). You should be getting them from `importlib.metadata`, which is the canonical metadata source. I do like `__version__`, so we [provide that](https://github.com/pybind/pybind11/blob/a48ec3e8820064511aac5fab71706166bdd590d3/pybind11/__init__.py#L8), but the others should only be metadata. `__version__` is slightly special since if something is broken (including a broken package install with invalid metadata), knowing the version can help pin down what is wrong.

**Comment by henrywoo** [comment]
Sorry if I was not clear. What I meant is I can't specify the author, version etc information in the python module written with pybind11. For example, I can specify `__doc__`. I want to do the same for `__version__`, `__author__` etc.

**Comment by henryiii** [comment]
Oh, why not? `m.attr("__version__") = "1.2.3"`, etc?

**Comment by henrywoo** [comment]
Is that C++ syntax? I want the information inside the `.so` file.

**Comment by henryiii** [comment]
Yes, that's C++. I can add the semicolon. ;)

```cpp
PYBIND11_MODULE(whatever, m) {
    m.attr("__version__") = "1.2.3";
}
```

**Comment by henrywoo** [comment]
I see. It seems we can put all the meta data using this way. I will give it a try.

**Comment by Skylion007** [comment]
@henryiii Presuming this worked for you and closing this issue. Reopen if that's not the case.
