### ISSUE TITLE
Dynamically adding methods upon class instantiation

### ISSUE THREAD

**Issue by bradharmon** [pybind/pybind11#431]
I would like to be able to dynamically add methods upon class instantiation, but have not been able to piece together how to make this happen.  The following example will segfault when trying to add the method within `__init__`.

```
#include "example.h"

class Example1 {
public:
    Example1() {}
    const char *foo = "foo";
};

void init_ex1(py::module &m) {
    py::class_<Example1> example1(m, "Example1");

    example1
        .def("__init__", [&](Example1 &instance) {
           new (&instance) Example1();

           /* Dynamically add a method upon class instantiation */
           example1.def(instance.foo, [](Example1 &self){});
        })
        .def("fake", [](Example1 &self){});
}
```

```
#!/usr/bin/env python
from __future__ import print_function
import sys
sys.path.append('.')

from example import Example1

instance1 = Example1()
```

Is there a supported way of doing this that I'm missing?

**Comment by jagerman** [comment]
You can, in theory, declare methods inside one of the lambdas, but it definitely doesn't have the effect you want: you can only declare them on the class, rather than the instance, so you'll just end up with a bunch of duplicate definitions (or possibly an error), and the first of the definitions will be called by *any* object's `foo()` method.  So not what you want.

One way you could work around this is to instead add a `std::function<void()> foo;` member to the Example1 class.  This then lets you set `instance.foo = []() { ... };` in your constructor, and bind it with: `example1.def_readonly("foo", &Example1::foo);` in the pybind definitions.  (Note: you'll need to `#include <pybind11/functional.h>` to make this work).

**Comment by bradharmon** [comment]
Thanks for the suggestion.  I am needing something a little more dynamic than this, however.  In my case, I will have multiple methods that need to be created and won't be known until runtime.  Currently I have implemented a `__getattr__` that returns a `cpp_function` lambda with captured variables, but this has the downside of not being able to introspect the available methods at runtime from the Python side.

**Comment by wjakob** [comment]
This is related to having a ``__dict__`` within every object for use with the default ``__get/setattr__``. There was a PR here a while ago that introduced exactly this but caused mysterious breakage on some versions of python. It was closed/stashed away eventually because nobody stepped up to address the breakage.

**Comment by wjakob** [comment]
-> https://github.com/pybind/pybind11/pull/275

**Comment by bradharmon** [comment]
Thanks for the pointer to the PR.  I'll close this and take a further look at the PR because it looks like that is what I need.
