### ISSUE TITLE
int return type is long on Python 2

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#432]
This may actually be by design, but I couldn't find a reason for it in the documentation.
Functions that have return type `int` (as in `add` from the basic example) in C++ give a return type `long` in Python 2.

**Comment by wjakob** [comment]
Hi @pschella,

pybind11 started out as a pure Python 3 library, and Python 2 support was only added later on.
Working with Python 2's two different numeric types turned out to be very awkward, so I've decided to always map to ``long`` (which I suppose is what ``int`` corresponds to in Python 3).

Wenzel

**Comment by wjakob** [comment]
I'll close this ticket since I don't interpret it as an issue. Feel free to reopen otherwise.

**Comment by pschella** [comment]
Understood. If we really end up needing other behavior I might submit a patch. But I suspect we can work with the current behavior.
