### ISSUE TITLE
Possible compatibility issue with pytest?

### ISSUE THREAD

**Issue by mibieri** [pybind/pybind11#433]
I try to run some of the tests. Some of them start with:

```
import pytest

with pytest.suppress(ImportError):
    import numpy as np
```

Leads to:

```
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /pybind11/tests/test_numpy_array.py
Traceback (most recent call last):
  File "/pybind11/tests/test_numpy_array.py", line 3, in <module>
    with pytest.suppress(ImportError):
AttributeError: module 'pytest' has no attribute 'suppress'
```

Seems that `pytest` does not have that attribute `suppress`.

I think I have a version of `pytest` which is not compatible with `pybind11`. Which version am I supposed to use?

Seems that I have installed 3.0.3 by "Holger Krekel, Bruno Oliveira, Ronny Pfannschmidt, Floris Bruynooghe, Brianna Laugher, Florian Bruhin and others"

**Comment by dean0x7d** [comment]
I guess you're trying to run an individual test and you're calling `python <test_name>`. The problem is that pytest needs to be the test runner, so the correct call is `pytest <test_name>` or `python -m pytest <test_name>` (the latter lets you choose the Python version/executable). Pytest will first configure itself by look at the `conftest.py` file and then run the tests.

**Comment by wjakob** [comment]
I assume this is closed based on the thumbs-up by @mibieri
