### ISSUE TITLE
Data transfer between deques.

### ISSUE THREAD

**Issue by JendaPlhak** [pybind/pybind11#438]
Hi, I have a problem with memory management when I try to transfer big data from one deque to another.  
The problem is described on stackoverflow - [link](http://stackoverflow.com/questions/39997840/program-gets-killed-when-ulimit-on-memory-is-not-set). I am not sure whether it is more appropriate to repost it here or if this form is sufficient. If not, please let me know and I will make adequate changes.

**Comment by dean0x7d** [comment]
I've only had a quick look, so there may be other issues, but the main thing is that your class is not picklable. `concurrent` uses Python's `multiprocessing` module which passes arguments between processes by pickling and unpickling them. See the [Pickling support](http://pybind11.readthedocs.io/en/latest/advanced.html#pickling-support) docs to add the required methods to your class.

As for why it works when you limit virtual memory: My guess is that `concurrent`/`multiprocessing` falls back to a single process which does not require pickling.

However, do note that `multiprocessing` is extremely inefficient. It spawns new processes in order to bypass Python's GIL. You'll never be able to get the ideal memory usage with it, but that's not really a pybind11 issue.

**Comment by JendaPlhak** [comment]
Actually, I spawn threads, not processes. I am well aware of the Pythons multiprocessing pitfalls and pickle/unpickle methods. Though we have discussed the problem with colleague of mine and currently we assume it might be caused by the fact, that the data are allocated by one thread - one malloc arena and dealocated in another thread, hence the memory is not really released. Will post as soon as I test our hypothesis.

**Comment by dean0x7d** [comment]
Oh, sorry, I saw `concurrent` and jumped to the wrong conclusion way too early.

I've run your code on two different systems now, but it seems to run fine for me. Both with and without the executor, there is no crash and there is no RAM doubling (it stays at ~11 GB). The systems I tried it on are Ubuntu 15.10 with GCC 5.2.1 and macOS 10.11 with clang 8.0.0.

Is the ~11 GB of RAM important? Does it crash for you if `deque` uses less RAM?

**Comment by JendaPlhak** [comment]
Eventually, this turned out to really be problem of memory being freed in different thread then it was allocated therefore it belonged to different malloc arena. ([For reference see this](https://siddhesh.in/posts/malloc-per-thread-arenas-in-glibc.html)) I
Therefore it was probably completely unrelated to pybind (Although I was unable to replicate this behaviour with pure Python.) 

To your question - It doesn't crash when it uses less RAM because I got 32Gb of RAM in my notebook. However htop clearly showed memory being used twice even with smaller arrays.

**Comment by JendaPlhak** [comment]
I also write [an answer](http://stackoverflow.com/a/40068900/1474847) to my question on SO. Attaching it for reference.

**Comment by wjakob** [comment]
Ok, sounds good -- closing this then.
