### ISSUE TITLE
Link broken for "How can I reduce the build time?" in FAQ

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#456]
I've dug around in the source of pybind11 to no satisfaction, but I can't find the file ``example/example.cpp`` (or what it might have been renamed to) referred to in the FAQ page.  Where did it go/ what did it become?

**Comment by jagerman** [comment]
Indeed this is an outdated bit of documentation: we should write a quick example in the documentation.  It's still being done in the pybind test code, but it moved into `tests/pybind11_tests.cpp`, and the actual way it handles it is much nicer for test writers, but less useful as an example (it uses a static self-registration mechanism for tests now instead of a hard-coded set of initialization functions).

Here's what the documentation was referring to (from the v1.8.1 branch): https://github.com/pybind/pybind11/blob/v1.8/example/example.cpp; resurrecting a bit of that code into the FAQ entry is probably better than pointing the FAQ to the new code.

**Comment by jagerman** [comment]
Scratch that, we actually already *do* give the example code, so I think we should just remove the reference to the example (just submitted a PR to do this).
