### ISSUE TITLE
Bad cmake generator expression when LTO is not available

### ISSUE THREAD

**Issue by rdeits** [pybind/pybind11#639]
When LTO or ThinLTO detection fails (as it does with clang+linux), `pybind11Tools.cmake` produces an `lto_flag` like this: `$<:-flto>`, which causes cmake to error out with:

```
CMake Error at /home/rdeits/locomotion/drake-distro/build-clang/install/share/cmake/pybind11/pybind11Tools.cmake:141 (target_compile_options):
  Error evaluating generator expression:

    $<:-flto>

```

**Comment by rdeits** [comment]
I think the issue is that `HAS_LTO_FLAG` is just empty, rather than "0"

**Comment by rdeits** [comment]
I think you should be able to reproduce this either by using a version of clang with LTO problems (I am currently on `clang version 3.9.1-svn288847-1~exp1 (branches/release_39)` on ubuntu 14.04, or just by mangling the `-flto` flag in `pybind11Tools.cmake` to ensure that the test fails.

**Comment by jagerman** [comment]
Duplicate of/fixed in #604 (not merged yet, but give it a try).

**Comment by rdeits** [comment]
Sorry, didn't see that one. Will do.

**Comment by jagerman** [comment]
The underlying issue was a little more complicated--the lto flags also need to be added to the linker.  Your commit was essentially equivalent to my initial one, but then I realized that the detection was more broken, failing to detect LTO even when it should.  #604 completely replaces the detection with a much more robust one.

**Comment by rdeits** [comment]
Ok, awesome, thanks. I'm building our project with #604 now.
