### ISSUE TITLE
need help with vectorize

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#646]
I'm trying to see if I can use the broadcast capability of vectorize.  I tried writing a function so that it can accept 2 args, where either can be array_t<double> or <double>.  But it doesn't seem to work (although the problem seems to be with py::isinstance, not with broadcast itself:

```c++
  m.def("polar_to_rect", [](py::object r, py::object phi) {
      if ((py::isinstance<py::array_t<double>>(r) or py::isinstance<double>(r))
          and
          (py::isinstance<py::array_t<double>>(phi) or py::isinstance<double>(phi))) {
        // if (r.size() != phi.size())
        //   throw py::type_error("polar_to_rect size mismatch");
        return py::vectorize([](double x, double y) { return std::complex<double>(x*cos(y), x*sin(y)); })(r,phi);
      }
      else
        throw py::type_error("polar_to_rect unhandled type");
    });
```
```python
X = polar_to_rect (np.ones (10, dtype=float), 2.0)
```
```
---> 12 X = polar_to_rect (np.ones (10, dtype=float), 2.0)

TypeError: polar_to_rect unhandled type
```

**Comment by dean0x7d** [comment]
Replace `py::isinstance<double>` with `py::isinstance<py::float_>` and it's going to work (*). But I'm wondering, why not just use `py::vectorize` directly and let pybind11 do the type checks instead of doing it manually?

(*) Python's `float` is convertible to `double` but it's not necessarily an instance of `double`. Only `py::object`-derived types or a `py::class_` wrapped types are actually instances of a given type, while all others which use `type_caster` are only "convertible to", not "is instance". (Some types also only convertible under certain conditions which makes things more complicated.)

@pybind `py::isinstance` currently returns `false` for all `type_caster` types. I don't think it's correct (or practical) to extend `py::isinstance` to these types, but perhaps an exception might be more appropriate than a simple `false`. Thoughts?

**Comment by nbecker** [comment]
I'd love to just use py::vectorize.  I don't see how that can be done for
polymorphic functions.  Suppose I want to vectorize a function F, and I'd
like to apply it to float, double, and maybe various int or even
std::complex.  The function F fed to vectorize has to be declared to have
specific input types.  For example, consider mag_sqr(flt_t x) = x * x;  I
could write mag_sqr(double) = x * x, but then I would assume everything
would get converted to/from double if I passed an array of np.float32.

**Comment by wjakob** [comment]
You could implement your own wrapper around vectorize, which takes a function template as argument and then instantiates it explicitly for all sorts of different types. This sort of thing is way beyond the scope of pybind11 though.
