### ISSUE TITLE
segfault mystery

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#653]
Any ideas on this?  The 1st lambda captures value, the 2nd captures reference.
```
...
  py::object float32_obj = py::module::import("numpy").attr("float32");
...
  m.def("test1", [float32_obj](py::object r) {
      return PyObject_IsInstance(r.ptr(), float32_obj.ptr());
    });
  m.def("test2", [&float32_obj](py::object r) {
      return PyObject_IsInstance(r.ptr(), float32_obj.ptr());
...
```
```
print (test1(np.float32(4.0))) <<< this prints '1'
print (test2(np.float32(4.0))) <<< this segfaults
```

**Comment by dean0x7d** [comment]
No mystery there. The object being captured by reference is a function variable which is destroyed after the function returns (which is at module initialization time). By the time the wrapped function is called, the object captured by reference has long since been destroyed. This isn't anything specific to pybind11, it's just C++: don't capture function locals by reference.

Again, prefer the [Gitter room](https://gitter.im/pybind/Lobby) for quick questions.
