### ISSUE TITLE
Visual Studio 2015 update 3 ICEs when using the overload_cast example.

### ISSUE THREAD

**Issue by NOhs** [pybind/pybind11#710]
#### Issue description
I wanted to port my code that uses pybind11 on Linux to also run on Windows. However, I kept getting a C1001. I boiled it down to the use of `overload_cast`

#### Reproducible example code
I used the 64bit cmake VS generator

```cpp
#include "pybind11/pybind11.h"

struct Pet {
    Pet(const std::string &name, int age) : name(name), age(age) { }

    void set(int age_) { age = age_; }
    void set(const std::string &name_) { name = name_; }

    std::string name;
    int age;
};


PYBIND11_PLUGIN(pytest)
{
	namespace py = pybind11;
	py::module m(
        "pytest", 
        "Module description goes here.");

	py::class_<Pet>(m, "Pet")
		.def("set", py::overload_cast<int>(&Pet::set), "Set the pet's age")
		.def("set", py::overload_cast<const std::string &>(&Pet::set), "Set the pet's name");

    return m.ptr();
} 
```

```cmake
cmake_minimum_required(VERSION 3.6)
project(test_pybind11 CXX)
add_subdirectory(pybind11)
pybind11_add_module(pytest MODULE main.cpp)
```

Output from VS:

```
2> T:\test\pybind\main.cpp(21): fatal error C1001: An internal error has occurred in the compiler.
2>  (compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\symbols.c', line 28467)
2>   To work around this problem, try simplifying or changing the program near the locations listed above.
2>  Please choose the Technical Support command on the Visual C++
2>   Help menu, or open the Technical Support help file for more information
2>  T:\test\pybind\main.cpp(22): note: see reference to variable template 'const pybind11::detail::overload_cast_impl<int> overload_cast<int>' being compiled
```

**Comment by dean0x7d** [comment]
Thanks for the nice and short code example. I can definitely reproduce the issue with VS2015. However, it does seem to be a genuine compiler bug and it only happens in certain conditions. By changing the syntax of the `overload_cast` definition, I was able to fix this particular issue, but that just broke it in other cases (e.g. the [pybind11 test code](https://github.com/pybind/pybind11/blob/master/tests/test_methods_and_attributes.cpp#L182-L190)). It seems that VS2015 is quite sensitive to the syntax of the variable template definition and also where it's used. 

I've reported the bug to Microsoft [here](https://connect.microsoft.com/VisualStudio/feedback/details/3128437), although I'm not sure VS2015 will be seeing any more updates now. But the good news is that this does seem to be fixed in VS2017 which was able to compile anything I threw at it (with regard to `overload_cast` at least).

**Comment by NOhs** [comment]
That's good news. I just upgraded to VS2017.

**Comment by dean0x7d** [comment]
> I just upgraded to VS2017.

Glad to hear that. Note that there was a VS2017-specific issue that was recently fixed in master:
2d965d43a673d48fdce7bf1771f96a009e1e018a So just pull the latest pybind11 code if you encounter any problems. With that, I think everything is resolved for VS2017 and I guess I'll close this issue with: _VS2015 compiler bug. Can't fix. Update to VS2017._

**Comment by jagerman** [comment]
I think not seeing another VS 2015 update is highly likely; I just saw [this from a Microsoft developer on the boost mailing list](http://lists.boost.org/Archives/boost/2017/03/233253.php):

> As far as the compiler and standard libraries are concerned, VS 2017 is a VS 2015 update release.

so it seems like VS 2017 *is* the next VS 2015 update.
