### ISSUE TITLE
use != instead of == in make_iterator

### ISSUE THREAD

**Issue by wojdyr** [pybind/pybind11#734]
a minor thing: using `!=` in make_iterator() would be compatible with C++11 range-based for.

I just noticed the difference when I tried to wrap a minimal C++ iterator that had `!=` to work with C++ for, but not `==`.

**Comment by jagerman** [comment]
Is this on 2.0 or master?  If 2.0, I think PR #662 should have addressed it.  If on master, I'm not understanding (the `iterator` returned by make_iterator has a `!=` operator).

**Comment by wojdyr** [comment]
In master. Sorry for not being clear, I meant `==` in the definition of `__next__` inside make_iterator:
```
.def("__next__", [](state &s) -> ValueType {
                if (!s.first)
                    ++s.it;
                else
                    s.first = false;
                if (s.it == s.end)
                    throw stop_iteration();
                return *s.it;
            }
```
and the fact that the range-based `for` in C++ uses `!=`:
```
    auto && __range = range_expression ;
    for (auto __begin = begin_expr, __end = end_expr;
            __begin != __end; ++__begin) {
```
So an iterator written with only C++ `for` in mind could be missing `==` and may not work as argument to make_iterator().
It's not really important and and I don't mind if this issue is just closed.

**Comment by jagerman** [comment]
While I suppose it is technically possible, it's a little bit unusual: such an iterator doesn't satisfy the [InputIterator concept](http://en.cppreference.com/w/cpp/concept/InputIterator)--it requires both `==` and `!=` operators, which means such an iterator won't work with many stl functions that take an InputIterator, either.

I think we should officially require a proper InputIterator here.  But if we had that requirement, we actually could switch it (and fix the test code iterator) so that for-range compatible iterators would work (though unofficially without a promise not to break them in the future).  On the other hand, requiring full InputIterators doesn't seem like a huge burden on users, either.

@wjakob, @dean0x7d - thoughts?

**Comment by dean0x7d** [comment]
Given that `InputIterator` is the minimal requirement for iterators in C++, I'd say it's perfectly valid to assume `==` exists. It would be trivial to work around it here, but then we need to maintain that stricter-that-the-cpp-standard policy going forward. Besides, an iterator that doesn't fulfill at least the `InputIterator` concept would run into problems eventually, with the STL or third-party libraries which also assume at least `InputIterator`.

**Comment by jagerman** [comment]
I added a change just now to explicitly document that we expect InputIterators.
