### ISSUE TITLE
unchecked vs. vectorize

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#760]
Attempt to use unchecked with vectorize fails to compile on master:

```
  m.def("mag_sqr", [](py::array_t<double> a) {
      auto b = a.unchecked<1>();
      // print ("double");
      return py::vectorize([](double x) {return x * x;})(b);
    },
    py::arg("in").noconvert()
    );
```
```
mag_sqr.cc:78:59: error: no match for call to '(pybind11::detail::vectorize_helper<pybind11_init()::<lambda(pybind11::array_t<double>)>::<lambda(double)>, double, double>) (pybind11::detail::unchecked_reference<double, 1l>&)'
       return py::vectorize([](double x) {return x * x;})(b);
...
```

**Comment by dean0x7d** [comment]
It isn't meant to compile. There is no advantage in giving `py::vectorize` an unchecked array since it already accesses the underlying data directly. It would not make it any faster.

Both methods are a form of fast array access and both work with the raw underlying data. The only difference is the access pattern and you should choose the one which is more convenient for your use case: `py::vectorize` works sequentially and must visit all the elements in the given array while `enchecked()` offers raw random access to any number of elements.
