### ISSUE TITLE
Static properties override

### ISSUE THREAD

**Issue by uentity** [pybind/pybind11#775]
Hello!

The question: do static properties override allowed by pybind11?

I have a base class, say `Foo` defined with its Python bindings in `module1`. Also I have a derived class `Bar: public Foo` defined with its Python bindings in `module2` (`pybind11::class_<Bar, Foo>`, i.e. base class `Foo` is passed as template argument to `pybind11::class_`). Both have static method `int test()` which I want to export to Python as static readonly property. I accomplish this with `.def_property_readonly_static` following the documentation.

But when `module2` is being loaded in Python interpreter I'm getting an exception: `AttributeError: can't set attribute`. I can fix this if I export `test()` as static function, i.e. with `.def_static` -- then everything seems to work properly. But overriding static properties doesn't work for me.

**Comment by uentity** [comment]
I've made an experiment -- If I place everything into single module, then error still persists. So, It seems to be not related to partitioning code over multiple modules.

**Comment by phfaist** [comment]
I stumbled upon the same problem: Overriding static properties worked with pybind11 version 2.0.1 (with the `py::metaclass()` annotation), but it no longer works with pybind11 version 2.1 (with or without `py::metaclass()`, which apparently is no longer needed).

[I'm attaching a minimal (non-)working example.](https://github.com/pybind/pybind11/files/903621/pybind11_overridestaticattr.tar.gz)

With pybind11 2.1.0, I get:
```
>>> import pybind11_overridestaticattr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: AttributeError: can't set attribute
```
whereas with pybind11 2.0.1, I get the expected behavior:
```
>>> import pybind11_overridestaticattr
>>> pybind11_overridestaticattr.A.IsBase
True
>>> pybind11_overridestaticattr.B.IsBase
False
```

Thanks!

**Comment by phfaist** [comment]
cool thanks !
