### ISSUE TITLE
`make check` issue

### ISSUE THREAD

**Issue by wojdyr** [pybind/pybind11#783]
as discussed on gitter, when I do:

    cmake -DPYTHON_EXECUTABLE:FILEPATH=python2 ..
  
then `make pylint` works but `make check` fails.

If full python path is given, i.e. `-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2`, both work.

BTW it seems that `make check` is not tested on travis.

**Comment by dean0x7d** [comment]
I'm not really sure that the first part is really a pybind11 issue since `PYTHON_EXECUTABLE` is simply handed over to CMake's [FindPythonInterp](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html) which does usually require a full path, not just the name. E.g. for me `cmake -DPYTHON_EXECUTABLE=python2 ..` fails right away, even before any tests.

`make check` is just a shortcut which invokes all the tests, i.e. same as `make pytest test_cmake_build` (but may include more in the future). Travis executes the same tests as `make check`, it just does it separately for log clarity and completeness (`make check` would exit on the first failure, but as separate commands Travis runs and reports everything).

**Comment by jagerman** [comment]
But it *does* work with `-DPYTHON_EXECUTABLE:FILEPATH=python2` (without the `:FILEPATH`) it fails.  It is probably an easy enough fix to just change the `set(build_options ...)` in `tests/CMakeLists.txt` to add `:FILEPATH`, which won't hurt when it's a full path, and should fix this issue.

**Comment by dean0x7d** [comment]
Ah, indeed. I didn't know `:FILEPATH` changed the behavior in that way.
