### ISSUE TITLE
Having to EXACTLY specify all bases for exported type

### ISSUE THREAD

**Issue by uentity** [pybind/pybind11#797]
Consider the following example.
```C++
#include <pybind11/pybind11.h>
#include <iostream>

namespace py = pybind11;
using namespace pybind11::literals;

// classes
class objbase : public std::enable_shared_from_this< objbase > {
	int prop_ = 42;
public:
	virtual std::string name() const {
		return "objbase";
	}

	int prop() const { return prop_; }
};

class iface {
public:
	int n = 84;
	virtual int f() const = 0;
};

class mytype : public iface, public objbase {
public:
	std::string name() const override {
		return "mytype";
	}
	int f() const override {
		return 42;
	}
};
using sp_my = std::shared_ptr<mytype>;

// trampoline
template<class T = objbase>
class py_objbase : public T {
public:
	using T::T;

	std::string name() const override {
		PYBIND11_OVERLOAD(std::string, T, name);
	}
};

class py_iface : public iface {
public:
	using iface::iface;

	int f() const override {
		PYBIND11_OVERLOAD_PURE(int, iface, f);
	}
};

// bind mytype
class py_mytype : public py_iface, public py_objbase<mytype> {
public:
	int f() const override {
		PYBIND11_OVERLOAD(int, mytype, f);
	}
};

PYBIND11_PLUGIN(example) {
	py::module m("example");

	// bind objbase
	py::class_<objbase, py_objbase<>, std::shared_ptr<objbase>>(m, "objbase")
		.def(py::init<>())
		.def("name", &objbase::name)
		.def_property_readonly("prop", &objbase::prop)
		.def_property_readonly("refs", [](objbase& src) { return src.shared_from_this().use_count() - 1; })
	;

	// iface
	py::class_<iface, py_iface, std::shared_ptr<iface>>(m, "iface")
		.def("f", &iface::f)
	;

	// bind mytype
	py::class_<mytype, objbase, py_mytype, std::shared_ptr<mytype>>(m, "mytype")
		.def(py::init<>())
		.def("name", &mytype::name)
		.def("f", &mytype::f)
		.def_property_readonly("n", [](mytype& src){ return src.n; })
	;

	return m.ptr();
}
```
And now the Python test:
```Python
In [1]: import example

In [2]: a = example.mytype()

In [3]: a.prop
Out[3]: -95698912L

In [4]: a.refs
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-344df654650d> in <module>()
----> 1 a.refs

RuntimeError: bad_weak_ptr
```
Calling `a.prop` and `a.refs` is UB, because parent `objbase` was *not constructed correctly*. I've had a hard time to figure out what is wrong with this bindings (can you see it?).

Yes -- I've forgot to mention `iface` in template args list of `class_<mytype, ...`. OK, let's fix that:
```C++
	py::class_<mytype, iface, objbase, py_mytype, std::shared_ptr<mytype>>(m, "mytype")
		.def(py::init<>())
		.def("name", &mytype::name)
		.def("f", &mytype::f)
		.def_property_readonly("n", [](mytype& src){ return src.n; })
	;
```
Now simple Python test succeeds:
```Python
In [2]: a = example.mytype()

In [3]: a.prop
Out[3]: 42L

In [4]: a.refs
Out[4]: 1L
```
Is that an expected behaviour? If I omit some of bases -- this is considered an error?

**Comment by uentity** [comment]
Hmm, I experience weird things, checked hundred times that all bases are enumerated, but still my object from similar class hierarchy is constructed incorrectly in Python.

**Comment by jagerman** [comment]
The long answer is that you need to *either* specify multiple base classes (you don't need all: as long as you have at least 2 it's enough), or need to add the `py::multiple_inheritance()` tag.  See point 1 in the [multiple inheritance](http://pybind11.readthedocs.io/en/master/advanced/classes.html#multiple-inheritance) docs.

The long answer is that when you *don't* have multiple inheritance, a `Derived*` can be `reinterpret_cast` to a `Base*` (because the base class data is always at the beginning of a derived class; any fields the derived class adds come after the base class), and we rely on this in pybind.

That isn't valid with multiple inheritance: we need to go through a more complicated casting procedure to get to the base class.

But there's no way for us to tell (in straight C++) whether a class actually uses multiple inheritance, so we rely on the binding code: if you give us multiple bases, obviously there is multiple inheritance; but if you have multiple inheritance that isn't exposed to Python, as in this case, you need to add the tag to tell pybind that your class needs to take the more complicated casting path.

**Comment by jagerman** [comment]
(For the benefit of anyone else who has a similar future problem)

It took me a minute to work out your hierachy, but your `py::class_<mytype, objbase, py_mytype, std::shared_ptr<mytype>>` is a `py::class_<Class, BaseClass, Trampoline, Pointer>` structure, i.e. it has just one base class (and so pybind doesn't know about the multiple inheritance).

**Comment by uentity** [comment]
Thank you very much for explanation. Again you showed me the detail I was missing.

**Comment by uentity** [comment]
My problem in real-world code is that I already have specified multiple bases for my type, *and* it wasn't working. So, adding `py::multiple_inheritance()` didn't help me actually.
Still trying to figure out what is wrong.. I' ll update this post to move it a bit more close to what I really have.
