### ISSUE TITLE
PYBIND11_NUMPY_DTYPE does not work on structure containing array

### ISSUE THREAD

**Issue by bmerry** [pybind/pybind11#800]
#### Issue description

Using PYBIND11_NUMPY_DTYPE on a structure member which is an array (either a language array or `std::array`) leads to a compilation error:
```
pybind11/numpy.h:1027:9: error: ‘format’ is not a member of ‘pybind11::format_descriptor<int [2]>’
         ::pybind11::format_descriptor<decltype(std::declval<T>().Field)>::format(),           \
         ^
```

#### Reproducible example code

```python
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <array>
#include <cstdint>

namespace py = pybind11;

struct foo
{
    std::int32_t array[2];
};

PYBIND11_PLUGIN(arraytest)
{
    PYBIND11_NUMPY_DTYPE(foo, array);

    py::module m("arraytest", "doc");
    return m.ptr();
}
```
Compiled with GCC 5.4 with `g++ -std=c++14 -c pybind11-array.cpp` plus `-I` options for Python and pybind11, and pybind11 version 2.1.1

**Comment by jagerman** [comment]
It's an [intentional, explicit omission](https://github.com/pybind/pybind11/blob/201796d94f29a6ab25628505c44c036d2dc43cad/include/pybind11/numpy.h#L235): not because it's impossible, but just because no one has done it yet.

**Comment by aldanor** [comment]
Well, almost... we wouldn't mark arrays as `is_pod_struct`, but rather specialise `npy_format_descriptor` and `format_descriptor`. In fact, we [do](https://github.com/pybind/pybind11/blob/201796d94f29a6ab25628505c44c036d2dc43cad/include/pybind11/numpy.h#L904) specialise those for `char[N]` and `std::array<char, N>`, mapping them to `S` dtype which is admittedly slightly hacky (since it overlaps with `int8_t[N]`, if we were to map arbitrary fixed-size arrays).

**Comment by bmerry** [comment]
I don't think it's likely to conflict with int8_t[N], because int8_t will be `signed char` and `char` is a distinct type from both `signed char` and `unsigned char`.

I might have a go at it if I get time, although it won't be this week.
