### ISSUE TITLE
Bindings for function returning shared_ptr<void> could not be compiled

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#820]
Hi developers,

I noticed that the following code lead to a compilation error (below). Is this expected? (Since we allow bindings for void* types then it seems reasonable to allow `std::shared_ptr<void>` as well...)

Thanks,

Sergey.

```C++
#include <pybind11/pybind11.h>

std::shared_ptr<void> foo()
{
	return nullptr;
}

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	m.def("foo", &foo);

    return m.ptr();
}
```

**Comment by lyskov** [comment]
In case this would help, here the error i am getting when compiling this:
```
In file included from /home/benchmark/src/pybind11/include/pybind11/pybind11.h:36:
In file included from /home/benchmark/src/pybind11/include/pybind11/attr.h:13:
/home/benchmark/src/pybind11/include/pybind11/cast.h:387:36: error: cannot form a reference to 'void'
    static handle cast(const itype &src, return_value_policy policy, handle parent) {
                                   ^
/home/benchmark/src/pybind11/include/pybind11/cast.h:839:82: note: in instantiation of template class 'pybind11::detail::type_caster_base<void>' requested here
template <typename type, typename holder_type> class type_caster_holder : public type_caster_base<type> {
                                                                                 ^
/home/benchmark/src/pybind11/include/pybind11/cast.h:953:48: note: in instantiation of template class 'pybind11::detail::type_caster_holder<void, std::shared_ptr<void> >' requested here
class type_caster<std::shared_ptr<T>> : public type_caster_holder<T, std::shared_ptr<T>> { };
                                               ^
/home/benchmark/src/pybind11/include/pybind11/pybind11.h:140:29: note: in instantiation of template class 'pybind11::detail::type_caster<std::shared_ptr<void>, void>' requested here
            handle result = cast_out::cast(args_converter.template call<Return>(cap->f),
                            ^
/home/benchmark/src/pybind11/include/pybind11/pybind11.h:49:9: note: in instantiation of function template specialization 'pybind11::cpp_function::initialize<std::shared_ptr<void> (*&)(), std::shared_ptr<void>, pybind11::name,
      pybind11::scope, pybind11::sibling>' requested here
        initialize(f, f, extra...);
        ^
/home/benchmark/src/pybind11/include/pybind11/pybind11.h:567:22: note: in instantiation of function template specialization 'pybind11::cpp_function::cpp_function<std::shared_ptr<void>, pybind11::name, pybind11::scope, pybind11::sibling>'
      requested here
        cpp_function func(std::forward<Func>(f), name(name_), scope(*this),
                     ^
shared-ptr-void.cpp:13:4: note: in instantiation of function template specialization 'pybind11::module::def<std::shared_ptr<void> (*)()>' requested here
        m.def("foo", &foo);
```

**Comment by jagerman** [comment]
The error isn't all that surprising: it isn't valid to dereference a `shared_ptr<void>`.  In order for it to become useful (or even usable) in C++ you need to `std::{static,dynamic,reinterpret}_pointer_cast` it to some type based on some external type information.  Even though pybind can, technically, bind a `void *`-returning function, it doesn't do anything particularly useful: it just becomes `None`.  It does that mainly to support casting a `void` function (rather than a `void *`) because it avoids needing to add special case for `void` functions.

The pybind behaviour of allowing binding a `void *` function is sort of accidental: a `void *` or a `shared_ptr<void>` is really something fundamentally different: it's a pointer to an unknown type which is really only useful when combined with the type via some other means.  But for a `void *` or `shared_ptr`-equivalent, pybind doesn't have the type, so there's really no way that this can be meaningfully returned to Python.  At best you'd get a `None` in Python, but it actually seems better to me to just not allow that--and, in fact, to even disallow binding a function that returns a `void *`.  Not because it wouldn't be useful, but because there's no way to get the type out of it, and without the type there's no way to do anything with it.

**Comment by lyskov** [comment]
Hmm... i would argue that there is a very good case for binding `void *` (and `std::shared_ptr<void>`): there is API's out there that create objects of type `void *` and later accept such pointers. For example, this particular case came from API that have function similar to:
```C++
std::shared_ptr<void> allocate_resource();
void use_resource(std::shared_ptr<void>);
void deallocate_resource(std::shared_ptr<void>)
```
(In this case reason for using `void *` pointers is because underlying object is just chunk of bits with no functionality what so ever. Iits not my API so would refer to discuss either this good practice/idea or not).

My point is that bindings for `std::shared_ptr<void>` could be useful when dealing with such C-style API's.

**Comment by jagerman** [comment]
Oh, I agree that in C++ it's very useful (pybind itself is full of `void *`s).  The issue is that we really have no way for them to survive the round trip from C++ -> Python -> C++ again; even if you return one, the pointer itself is discarded and you just end up with `None` in Python.

**Comment by jagerman** [comment]
In that specific case, you'd probably be best off encapsulating it--perhaps in a `pybind11::bytes` object if that suits your needs, or in a thin wrapper along the lines of `struct Data { std::shared_ptr<void> data; Data(std::shared_ptr<void> d) : data{d} {}; operator std::shared_ptr<void>() { return data; }`.  It's not the prettiest, but it'll give you an opaque object that can go through the conversion untouched.

**Comment by lyskov** [comment]
Wait, i thought that values of `void *` is preserved... no? Like if i have bonded C++ that return `void *` and i later pass it to other function - that later function will be getting exactly the same value. Is this so?

And if yes, - can we do the same for shared_ptr?

**Comment by jagerman** [comment]
Oh, you're right, I didn't know that we actually did that!

**Comment by jagerman** [comment]
Okay, scratch what I wrote above, this actually does seem reasonable to me in that case.

**Comment by lyskov** [comment]
Yay! - thank you!

**Comment by jagerman** [comment]
So it turns out you can do this yourself (without any pybind changes) with just two lines:

```C++
PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>);
```
and then in your definitions somewhere:
```C++
py::class_<std::shared_ptr<void>>(m, "encapsulated_data");
```

That's actually a bit easier than doing it in pybind11 itself: we can't encapsulate the pointer in a plain python capsule because we also have to preserve the `shared_ptr<void>` instance (because its destruction might invalidate the pointer).  So it really has to be a wrapped type, i.e. we have to wrap the `std::shared_ptr<void>`, not just the `void *`, and so we need a custom type.

**Comment by lyskov** [comment]
Awesome, seems to be working for me - thank you @jagerman !
