### ISSUE TITLE
Constructor taking a numpy array

### ISSUE THREAD

**Issue by mbrucher** [pybind/pybind11#876]
Hi,
I want to be able to do something like this:

import numpy as np
d = np.zeros(10, dtype = np.float64)
my_instance = PyModule.MyClass(d, xxx)

and this would turn into a call to the constructor:
MyClass(std::size_t count, double ptr, xxx)

with lambdas, I thin I can do it for member function, but what about the constructor? Also a lambda with a function named "__init__"?

**Comment by mbrucher** [comment]
OK, I found another tutorial with the anwser. __init__ allows in place constructor calls with a lambda, that's great!
Two more questions: how are default args defined? I tried def("__ini__", [](MyClass& instance, const pyarray_t<float>& array, bool arg2){}, py::arg("arg2")=false), but I got "The number of argument annotations does not match the number of function arguments".
Last question: are py_array_t<> converted from one type to another? I'd like to forbid my user to specify the wrong numpy type, as I will write to the numpy array during the life of the object.

**Comment by jagerman** [comment]
`py::arg`s are matched to arguments by relative position, so you need to specify one `py::arg` for each argument (not including the `self` parameter), so that we can match up `py::arg`s with function arguments.  C++ doesn't have introspection, so there's no way for us to know that the "arg2" you gave matches the second argument.

As for avoiding conversion, see the [noconvert](http://pybind11.readthedocs.io/en/stable/advanced/functions.html#non-converting-arguments) flag; if it's specified for the `array_t` argument, it won't let the user call it with something that would require conversion (wrong dtype) or coercion (e.g. from a list).

Putting both together, you want: `def("__init__", [](...){ ... }, py::arg().noconvert(), py::arg("arg2") = false)`.  (You can name the first argument as well if you want, but it isn't necessary).

**Comment by mbrucher** [comment]
Amazing, no other words.
Thanks a lot!
