### ISSUE TITLE
Question: how to set the name attribute for py::capsule?

### ISSUE THREAD

**Issue by phaustin** [pybind/pybind11#894]
Is it possible to embed the function signature as a string in py::capsule?  This is needed for the new [scipy lowlevelcallable](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.LowLevelCallable.html) interface -- something like cython's [PyCapsule_New](https://github.com/cython/cython/blob/53c184fd5fc1e2916b56ac8a76689ee3c7015a2a/Cython/Includes/cpython/pycapsule.pxd#L28-L29)

I don't seem to see it in [pytypes.h](https://github.com/pybind/pybind11/blob/master/include/pybind11/pytypes.h)

thanks, Phil

**Comment by jagerman** [comment]
Not currently supported, I'm afraid, but we'd happily accept a PR to add it.

(It would be quite easy to do by adding an optional `const char *name = nullptr` argument to the various `capsule` constructors in `pytypes.h`, then passing that (instead of `nullptr`) as the second `PyCapsule_New` argument.  Thus plus a test suite addition to verify that it's working ought to do it).

**Comment by phaustin** [comment]
Easy enough for the first constructor:
https://github.com/pybind/pybind11/commit/c5d2a6813d39385cc6c51d1ca6f6abde92de4d29

but for the other, would it mean adding name as the third optional argument, so changing the argument order from that expected for PyCapsule_New?

**Comment by jagerman** [comment]
The reversed order doesn't really bother me, especially since the destructor seems more likely to be given than the name.

**Comment by phaustin** [comment]
ok, see https://github.com/pybind/pybind11/pull/902

**Comment by jagerman** [comment]
Closed via #902.
