### ISSUE TITLE
No TypeError when converting negative int to unsigned 64bit on Windows

### ISSUE THREAD

**Issue by ariaTim** [pybind/pybind11#929]
### Issue
Function argument type conversion from negative python integer to unsigned 64 bit c++ type does not raise TypeError. For a 32 bit unsigned type a TypeError is thrown as expected.

Note: It doesn't happen on Linux (with gcc 7.0.1) perhaps because `uint64_t` is an alias for `unsigned long` where as on Windows with VS 2017 `uint64_t` is an `unsigned long long`.

Occurs on:
Windows 10 (VS 2017)
pybind11 2.1.1 and master ( 30f6c3b )

### Example
cpp:
```cpp
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(IntTest, m)
{
    m.def("take_uint64", [](uint64_t val)
    {
        py::print("taken uint64: ", val);
    });

    m.def("take_uint32", [](uint32_t val)
    {
        py::print("taken uint32: ", val);
    });
}
```
python:
```python
from IntTest import *

try:
    take_uint32(-1)
except TypeError as e:
    assert "take_uint32(): incompatible function arguments." in str(e)

take_uint64(-1)

```
example output:
```
taken uint64:  4294967295
```

**Comment by jagerman** [comment]
I could reproduce this under 32-bit linux under Python 2 as well (your hunch was correct: it happens anywhere `sizeof(long) == 4`).

The main issue is that that the `4294967295` value is an error value python returned, but because we cast it to a `uint64_t` before checking for an error, we don't get the `value == (uint64_t) -1` error condition (because `(uint64_t) -1` is 18446744073709551615, not 4294967295.

Under Python 3, it's a bit trickier to hit the same error: you'd have to (I think) be binding an exotic integer type (e.g. gcc's `__uint128_t`) larger than an `unsigned long long`.  So rare, but still an issue.

#931 should fix it.

**Comment by jagerman** [comment]
Thanks for the report—the fix is applied to `master` now.
