### ISSUE TITLE
Handling python exceptions

### ISSUE THREAD

**Issue by msis** [pybind/pybind11#946]
Can't figure out how to pass python exceptions properly.
Here are the steps taken following the documentation:

1. I created a module specific expection : [`pyMOOSException`](https://github.com/msis/python-moos/blob/setuppy/src/pyMOOS.cpp#L21:L27)
1. Regitered [exception translator](https://github.com/msis/python-moos/blob/setuppy/src/pyMOOS.cpp#L533:L542)
1. Tried [catching][trycatch] exceptions at the callbacks 

With that, exceptions are *all* converted to `pyMOOSException`, therefore making it very opaque: all other python related expceptions (`SyntaxError`, etc.) are not raised and converted to `pyMOOSExpcetion`.

I feel like something needs to be added in the try catch [blocks][trycatch].

Any suggestions to solve this issue?

[trycatch]: https://github.com/msis/python-moos/blob/setuppy/src/pyMOOS.cpp#L98:L105

**Comment by jagerman** [comment]
Perhaps I'm not following, but:

> With that, exceptions are all converted to pyMOOSException, therefore making it very opaque

That seems to be exactly what step 3. does: it catches any underlying Python exception and wraps it in a pyMOOSException; the added exception handler then catches this wrapped exception.

**Comment by msis** [comment]
But what if I want to differentiate between the `C++` caused exceptions and the standard `python` exceptions?

**Comment by jagerman** [comment]
I'm afraid I'm not following.  Can you give a concrete example of two different exceptions you're trying to differentiate between?

**Comment by jagerman** [comment]
If the exception is coming directly from C++ (i.e. not through a Python function), you should just catch it directly rather than catching `error_already_set`.

If the exception is propagated through Python, you'll need to define a custom python exception type and look for it when catching an `error_already_set`.  In your current example, you can do this by changing the exception translator to:
```C++
    static py::exception<pyMOOSException> ex(m, "pyMOOSException", PyExc_RuntimeError);
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const pyMOOSException &e) {
            // Set pyMOOSException as the active python error
            ex(e.what());
        }
    }
```
then when you catch `error_already_set` you can check whether the Python-side pyMOOSException is the active exception with:
```C++
try { ... }
catch (const py::error_already_set &e) {
    auto py_moos_exc = py::module::import("modulename").attr("pyMOOSException");
    if (e.matches(py_moos_exc.ptr())) {
        // intercepted a pyMOOSException
    } else {
        throw; // Some other python exception: rethrow it to the default exception translator
    }
}
```

You can simplify that a bit if you make the `ex` variable a global instead a function-static variable; then you don't have to get `py_moos_exc` via module lookup: you can just use `e.matches(ex.ptr())` directly instead.

**Comment by dean0x7d** [comment]
Looks like the last post answered this question. Feel free to reopen if there's anything else.
