### ISSUE TITLE
target not getting linked with a static library 

### ISSUE THREAD

**Issue by surabhi96** [pybind/pybind11#985]
I have a static library and I want to link it with the python extension module.
I do the following in my CMakeLists.txt 

`add_subdirectory(lib/pybind11)`
`pybind11_add_module(wrap_call_triangle ${SOURCE_DIR}/calltri.cpp ${SOURCE_DIR}/wrap_call_triangle.cpp)`
`set_target_properties(${BUILDTRI} PROPERTIES POSITION_INDEPENDENT_CODE TRUE)` #  to enable -fPIC for the dependency for the library set in ${BUILDTRI}
`target_link_libraries(wrap_call_triangle PRIVATE ${BUILDTRI})` # trying to link with static library.

But it gives the following error:
```
set_target_properties Can not find target to add properties to:
  ~/create_mesh/build/libcreatemesh.a 
```

Can someone help?
Thanks!

**Comment by dean0x7d** [comment]
As far as I can see here, the problem is on the line with `set_target_properties(${BUILDTRI} PROPERTIES POSITION_INDEPENDENT_CODE TRUE)` and not anything to do with pybind11. Make sure that `${BUILDTRI}` contains a valid CMake target. Here, it looks like it's actually a file path. Based on the name, it's likely that you actually need `set_target_properties(createmesh PROPERTIES POSITION_INDEPENDENT_CODE TRUE)`.

Also, please post general questions in [pybind11's Gitter chat room](https://gitter.im/pybind/Lobby) since we'd like to keep the tracker specific to pybind11 issues.
