### ISSUE TITLE
Error: Incompatible function arguments

### ISSUE THREAD

**Issue by surabhi96** [pybind/pybind11#992]
I'm using pybind11 to access some functions which I wrote in C++ from python. I wish to return an initialized struct instance to python(from a class member function) so that I can access the instance values in python. I have provided a simplified version of my source file. One can reproduce the error with the following. This is the c++ wrapper

```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "sum.h"
namespace py = pybind11;

PYBIND11_PLUGIN(GetSum) {

py::module mod("GetSum", "wrapping caltri");

mod.def("get_instance", &GetSum::get_instance, py::return_value_policy::copy, "get instance of out");

py::class_<GetSum, std::shared_ptr<GetSum>>(mod, "GetSum") 
  .def(py::init<>())
  .def("input", &GetSum::input);

return mod.ptr();
}
```

This is a part of the class header sum.h

  ```
 extern "C" {
#include "mesh.h"
}
#include<iostream>
#include<vector>

class GetSum {
 struct A out;

 public:
  GetSum();
  void input(std::vector<float>);
  struct A get_instance() {   
   return out; };  
  ~GetSum();

};
```

This is class definition sum.cpp

```
#include "sum.h"

GetSum::GetSum() {
 out.pointlist = nullptr;
}
void GetSum::input(std::vector<float> num){ 
  out.pointlist = new float[num.size()];   
  for(size_t i = 0; i < num.size(); i++) 
      *(out.pointlist+i) = num[i]; 
}

GetSum::~GetSum(){
  delete [] out.pointlist;
}

```
Struct definition: mesh.h

```
#include <stdio.h>

struct A {
 float *pointlist;
};
```

and this is how I was calling it in python.

```
import GetSum
m = GetSum.GetSum()
m.input([1.0,2.0])
GetSum.s = GetSum.get_instance()
```

After which I get the error: get_instance(): incompatible function arguments. The following argument types are supported: 1. (arg0: GetSum) -> A

Can someone help me figure out where I might be going wrong?

Thanks!

**Comment by jagerman** [comment]
You're declaring `get_instance` at the module level as if it's a static method, but it isn't: it's an instance method (i.e. C++ member function).  Thus you end up with a Python function that expects the instance (i.e. `self`) as the first argument, just like an ordinary class instance function.

You'll need to update your binding code to make it a definition of the `py::class_`, and then update your Python code to call it as an instance method.

Alternatively you can change the C++ member function to a static function: `static struct A get_instance() { ... }`, but that would require other changes because the current code is returning a member variable.

**Comment by surabhi96** [comment]
Okay. This is what I have done 
```
py::class_<GetSum, std::shared_ptr<GetSum>>(mod, "GetSum") 
  .def(py::init<>())
  .def("get_instance",&GetSum::get_instance, py::return_value_policy::copy, "return instance")
  .def("input", &GetSum::input);

```
and used it in python as follows and it gives TypeError: Unable to convert function return value to a Python type! The signature was
	(self: GetSum.GetSum) -> A. 
import GetSum
```
m = GetSum.GetSum()
m.input([1.0,2.0])
c = GetSum.GetSum()
c = m.get_instance() 
```

**Comment by YannickJadoul** [comment]
That's because you have not exposed class A to Python (or told pybind11 what else to do with it). So pybind11 has no clue how to convert that returned object (see error message).

By the way, there's a [Gitter chat box](https://gitter.im/pybind/Lobby) set up for this repository (see README), and they like to keep these kinds of questions that aren't bugs in pybind11 for that conversation, instead of having them logged as issues on GitHub.

**Comment by surabhi96** [comment]
It is struct A. Yes, how do I do that? 
Oh, I'm sorry. Are there seperate channels in the chat box? Because I see only a single channel where everyone seems to be posting questions.

**Comment by YannickJadoul** [comment]
The same way as you just did with that class GetSum. The C++ compiler does not make a real distinction between classes and structs (except for the default access specifier being respectively private and public). So, just `py::class_<A, whatever_else>(mod, "A")` will do.

I don't think there are different channels (though that might be a good idea), but even in what seems rather chaotic, things get answered rather quickly :-)
